
local cfg = {}

cfg.attachments = {
    "COMPONENT_CARBINERIFLE_CLIP_02",
    "COMPONENT_AT_AR_FLSH",
    "COMPONENT_AT_RAILCOVER_01",
    "COMPONENT_AT_SCOPE_SMALL",
    "COMPONENT_AT_SCOPE_MEDIUM",
    "COMPONENT_AT_SCOPE_MACRO",
    "COMPONENT_AT_AR_SUPP",
    "COMPONENT_SPECIALCARBINE_CLIP_01",
    "COMPONENT_ASSAULTRIFLE_CLIP_03",
    "COMPONENT_ASSAULTRIFLE_CLIP_02",
    "COMPONENT_ASSAULTRIFLE_MK2_CLIP_02",
    "COMPONENT_PISTOL_CLIP_02",
    "COMPONENT_AT_PI_FLSH",
    "COMPONENT_AT_PI_SUPP",
    "COMPONENT_MACHINEPISTOL_CLIP_02",
    "COMPONENT_MACHINEPISTOL_CLIP_03",
    "COMPONENT_MICROSMG_CLIP_02",
    "COMPONENT_AT_AR_SUPP_02",
    "COMPONENT_COMBATPDW_CLIP_02",
    "COMPONENT_AT_AR_AFGRIP",
    "COMPONENT_COMBATPDW_CLIP_03",
    "COMPONENT_SMG_MK2_CLIP_02",
    "COMPONENT_AT_SCOPE_MEDIUM_MK2",
    "COMPONENT_PISTOL50_CLIP_02",
    "COMPONENT_SPECIALCARBINE_CLIP_02",
    "COMPONENT_COMBATPISTOL_CLIP_02",
    "COMPONENT_AKM_CLIP_02",
    "COMPONENT_HKG3_CLIP_02"
}

return cfg
