RegisterNUICallback("exit",function(a)
    SetDisplay(false)
    stopAnim()
end)
RegisterNUICallback("personsearch",function(a)
    TriggerServerEvent("ARMA:searchPerson", a.firstname, a.lastname)
end)
RegisterNUICallback("platesearch",function(a)
    TriggerServerEvent("ARMA:searchPlate", a.plate)
end)
RegisterNUICallback("submitfine",function(a)
    TriggerServerEvent("ARMA:finePlayer", a.user_id, a.charges, a.amount, a.notes)
end)
RegisterNUICallback("addnote",function(a)
    TriggerServerEvent("ARMA:addNote", a.user_id, a.note)
end)
RegisterNUICallback("removenote",function(a)
    TriggerServerEvent("ARMA:removeNote", a.user_id, a.note)
end)
RegisterNUICallback("addattentiondrawn",function(a)
    TriggerServerEvent("ARMA:addAttentionDrawn", a)
end)
RegisterNUICallback("removeattentiondrawn",function(a)
    TriggerServerEvent("ARMA:removeAttentionDrawn", a.ad)
end)
RegisterNUICallback("savenotes",function(a)
    TriggerServerEvent("ARMA:updateVehicleNotes", a.notes, a.user_id, a.vehicle)
end)
RegisterNUICallback("savepersonnotes",function(a)
    TriggerServerEvent("ARMA:updatePersonNote", a.user_id, a.notes)
end)
RegisterNUICallback("generatewarrant",function(a)
    TriggerServerEvent("ARMA:getWarrant")
end)
RegisterNUICallback("addpoint",function(a)
    TriggerServerEvent("ARMA:addPoints", a.points, a.id)
end)
RegisterNUICallback("addmarker",function(a, b)
    TriggerServerEvent("ARMA:addWarningMarker", tonumber(a.id), a.type, a.reason)
    b()
end)
RegisterNUICallback("wipeallmarkers",function(a, b)
    TriggerServerEvent("ARMA:wipeAllMarkers", a.code)
    b()
end)
RegisterNetEvent("ARMA:sendSearcheduser",function(c)
    SendNUIMessage({type = "addPersons", user = c})
end)
RegisterNetEvent("ARMA:sendSearchedvehicle",function(d)
    SendNUIMessage({type = "displaySearchedVehicle", vehicle = d})
end)
RegisterNetEvent("ARMA:addADToClient",function(e)
    SendNUIMessage({type = "updateAttentionDrawn", ad = e})
end)
RegisterNetEvent("ARMA:verifyFineSent",function(f, g)
    SendNUIMessage({type = "verifyFine", sentornah = f, msg = g})
end)
RegisterNetEvent("ARMA:novehFound",function(g)
    SendNUIMessage({type = "noveh", message = g or "No vehicles found!"})
end)
RegisterNetEvent("ARMA:openPNC",function(h, i, e)
    SetNuiFocus(true, true)
    SendNUIMessage({type = "ui",status = true,id = tARMA.getUserId(),name = GetPlayerName(PlayerId()),gc = h,news = i,ad = e})
    startAnim()
end)
RegisterNetEvent("ARMA:updateAttentionDrawn",function(j)
    SendNUIMessage({type = "updateAttentionDrawn", ad = j})
end)
RegisterNetEvent("ARMA:setNameFields",function(k, l)
    SendNUIMessage({type = "setNameFields", lname = k, fname = l})
end)
RegisterNetEvent("ARMA:noPersonsFound",function()
    SendNUIMessage({type = "NoPersonsFound"})
end)
CreateThread(function()
    while true do
        if IsControlJustPressed(0, 168) then
            TriggerServerEvent("ARMA:checkForPolicewhitelist")
        end
        Citizen.Wait(0)
    end
end)
function startAnim()
    CreateThread(function()
        RequestAnimDict("amb@world_human_seat_wall_tablet@female@base")
        while not HasAnimDictLoaded("amb@world_human_seat_wall_tablet@female@base") do
            Citizen.Wait(0)
        end
        attachObject()
        TaskPlayAnim(tARMA.getPlayerPed(),"amb@world_human_seat_wall_tablet@female@base","base",8.0,-8.0,-1,50,0,false,false,false)
    end)
end
function attachObject()
    tab = CreateObject("prop_cs_tablet", 0, 0, 0, true, true, true)
    AttachEntityToEntity(tab,tARMA.getPlayerPed(),GetPedBoneIndex(tARMA.getPlayerPed(), 57005),0.17,0.10,-0.13,24.0,180.0,180.0,true,true,false,true,1,true)
end
function stopAnim()
    StopAnimTask(tARMA.getPlayerPed(), "amb@world_human_seat_wall_tablet@female@base", "base", 8.0)
    DeleteEntity(tab)
end
function SetDisplay(f)
    SetNuiFocus(f, f)
    SendNUIMessage({type = "ui", status = f, name = GetPlayerName(PlayerId())})
end
function PoliceSeizeTrunk(n, o)
    TriggerServerEvent("ARMA:policeClearVehicleTrunk", n, o)
end
RegisterNetEvent("ARMA:notifyAD",function(g, p)
    tARMA.notifyPicture("met_logo", "met_logo1", g, "Met Control", p, "police", 2)
end)
