vRPAmmoTypes = {
    ["357 Bullets"] = {"WEAPON_SVD", "WEAPON_BORA"},
    ["5.56 NATO"] = {"WEAPON_WINCHESTER12","WEAPON_AUG","WEAPON_g36k"},
    ["7.62 Bullets"] = {"WEAPON_m4a1", "WEAPON_mcx", "WEAPON_SCAR", "WEAPON_akkal", "WEAPON_MOSIN", "WEAPON_M16A4", "WEAPON_CHUCKY","WEAPON_ASSAULTRIFLE_MK2","WEAPON_SNIPERRIFLE"},
    ["9mm Bullets"] = {"WEAPON_M1911", "WEAPON_FNP", "WEAPON_PDW", "WEAPON_glock17", "WEAPON_mp5","WEAPON_PPSH"},
}