weapons = {}

weapons.weaponNames = {
    ["WEAPON_M4A4FIRE"] = {"M4A4 Fire"},
    ["WEAPON_VTSGLOW"] = {"VTS Glow"},
    ["WEAPON_M4A1WHITENOISE"] = {"M4A1 Whitenoise"},
    ["WEAPON_BLASTXPHANTOM"] = {"Blast X Phantom"},
    ["WEAPON_CHERRYMOSIN"] = {"Cherry Mosin"},
    ["WEAPON_UMP45"] = {"UMP-45"},
    ["WEAPON_REVOLVER357"] = {"Revolver 357"},
    ["WEAPON_ROOK"] = {"Rook-40"},
    ["WEAPON_SVD"] = {"Dragunov SVD"},
    ["WEAPON_M1911"] = {"M1911"},
    ["WEAPON_SPAR16"] = {"Spar 16"},
    ["WEAPON_M4A1"] = {"M4A1"},
    ["WEAPON_AK74KASHNAR"] = {"AK74 Kashnar"},
    ["WEAPON_WINCHESTER12"] = {"Winchester 12"},
    ["WEAPON_UZI"] = {"Uzi"},
    ["WEAPON_MOSIN"] = {"Mosin Nagant"},
    ["WEAPON_AK200"] = {"AK200"},
    ["WEAPON_AK47"] = {"AK47"},
    ["WEAPON_TEC9"] = {"Tec-9"},
    ["WEAPON_STAFFGUN"] = {"Staff Gun"},
    ["WEAPON_DIAMONDSWORD"] = {"Diamond Sword"},
    ["WEAPON_SHANK"] = {"Shank"},
    ["WEAPON_BROOM"] = {"Broom"},
    ["WEAPON_BASEBALLBAT"] = {"BaseBall Bat"},
    ["WEAPON_AXE"] = {"Axe"},
    ["WEAPON_SHOVEL"] = {"Shovel"},
    ["WEAPON_DILDO"] = {"Dildo"},
    ["WEAPON_MXC"] = {"MXC"},
    ["WEAPON_PDHK416"] = {"HK416"},
    ["WEAPON_REMINGTON700"] = {"Remington 700"},
    ["WEAPON_GLOCK"] = {"GLOCK"},
    ["WEAPON_PDMCX"] = {"SIG MCX"},
    ["WEAPON_CQ300"] = {"CQ300"},
    ["WEAPON_SPAR17"] = {"Spar 17"},
    ["WEAPON_MP5"] = {"MP5"},
    ["WEAPON_REMINGTON870"] = {"Remington 870"},
}

return weapons
