
local cfg = {}

-- define each group with a set of permissions
-- _config property:
--- gtype (optional): used to have only one group with the same gtype per player (example: a job gtype to only have one job)
--- onspawn (optional): function(player) (called when the player spawn with the group)
--- onjoin (optional): function(player) (called when the player join the group)
--- onleave (optional): function(player) (called when the player leave the group)
--- (you have direct access to vRP and vRPclient, the tunnel to client, in the config callbacks)
--  special (optional) -- defines whether user needs special permissions to remove this group.
-- If you have a special group the prefix of the permission is player.manage_groupname An example would be: player.manage_superadmin 
--[[

Hi, It's JamesUK#6793 Here. 

	"vrp.adminmenu", 
    "player.kick",
    "player.ban",
	"player.revive",
	"player.slap",
	"player.spectate", 
	"player.tpto", 
	"player.tpbring",
	"player.removeGroups",
	"player.addGroups",
	"player.manage_superadmin",
	"player.manage_saadmin",
	"player.manage_admin",
	"player.manage_mod",
	"player.manage_support",
	"player.manage_trial", 
	"player.propcleanup", 
	"player.pedcleanup", 
	"player.vehcleanup",
	"player.cleanallcleanup",
	"player.shutdownserver",
	"player.addcar",
	"player.tptowaypoint",
	"admin.spawnveh",
	"admin.removewarning",
	"player.addblacklistedprops" -- Allows live updating of blacklisted props only give to trusted staff.

	These are all the perms for the latest RageUI update, many thanks JamesUK.


]]


cfg.groups = {
--[[		OLD STAFF PERMS
		["dev"] = {

        "dev.menu",
        "dev.spawncar",
        "dev.spawnweapon",
        "dev.deletecar",
        "dev.fixcar",

        "admin.menu",
        "admin.warn",
        "admin.showwarn",
        "admin.ban",
        "admin.kick",
        "admin.nof10kick",
        "admin.revive",
        "admin.tp2player",
        "admin.summon",
        "admin.freeze",
        "admin.getgroups",
        "admin.spectate",
        "admin.screenshot",
        "admin.slap",
        "admin.givemoney",
        "admin.tp2waypoint",
        "admin.tp2coords",
		"admin.removewarn",
		"admin.spawnBmx",
		"admin.idsabovehead",
		"admin.noclip",
			
		"admin.staffAddGroups",
		"admin.povAddGroups",
		"admin.mpdAddGroups",
		"admin.licenseAddGroups",
		"admin.donoAddGroups",

		"group.add.vipgarage",
        "group.add.founder",
        "group.add.staffmanager",
        "group.add.commanager",
        "group.add.headadmin",
        "group.add.senioradmin",
        "group.add.administrator",
		"group.add.supportteam",
		"group.add.srmoderator",
        "group.add.moderator",
        "group.add.trial",
        "group.add",

		"group.remove.vipgarage",
        "group.remove.founder",
        "group.remove.staffmanager",
        "group.remove.commanager",
        "group.remove.headadmin",
        "group.remove.senioradmin",
        "group.remove.administrator",
        "group.remove.moderator",
        "group.remove.trial",
		"group.remove",
		
		"admin.whitelisted",
		"admin.tickets",
	},
	["founder"] = {
		"admin.menu",
        "admin.warn",
        "admin.showwarn",
        "admin.ban",
        "admin.kick",
        "admin.nof10kick",
        "admin.revive",
        "admin.tp2player",
        "admin.summon",
        "admin.freeze",
        "admin.getgroups",
        "admin.spectate",
        "admin.screenshot",
        "admin.slap",
        "admin.givemoney",
        "admin.tp2waypoint",
        "admin.tp2coords",
		"admin.removewarn",
		"admin.spawnBmx",
		"admin.noclip",
    	"staff.mode",
		"admin.vehmenu",
		"admin.spawnGun",
		"admin.addcar",
		"admin.idsabovehead",
		"admin.smartsigns",
		
		"admin.staffAddGroups",
		"admin.povAddGroups",
		"admin.mpdAddGroups",
		"admin.licenseAddGroups",
		"admin.donoAddGroups",
		"admin.nhsAddGroups",

		"group.add.vipgarage",
        "group.add.founder",
        "group.add.staffmanager",
        "group.add.commanager",
        "group.add.headadmin",
        "group.add.senioradmin",
        "group.add.administrator",
        "group.add.moderator",
        "group.add.trial",
        "group.add",

		"group.remove.vipgarage",
        "group.remove.founder",
        "group.remove.staffmanager",
        "group.remove.commanager",
        "group.remove.headadmin",
        "group.remove.senioradmin",
        "group.remove.administrator",
        "group.remove.moderator",
        "group.remove.trial",
		"group.remove",
		
		"admin.whitelisted",
		"admin.tickets",
		
		"vehicle.delete",
	},
	["staffmanager"] = {
		"admin.menu",
        "admin.warn",
        "admin.showwarn",
        "admin.ban",
        "admin.kick",
        "admin.nof10kick",
        "admin.revive",
        "admin.tp2player",
        "admin.summon",
        "admin.freeze",
        "admin.getgroups",
        "admin.spectate",
        "admin.screenshot",
        "admin.slap",
        "admin.tp2waypoint",
        "admin.tp2coords",
		"admin.removewarn",
		"admin.spawnBmx",
		"admin.noclip",
    	"staff.mode",
		"admin.idsabovehead",
		"vehicle.delete",
		
		"admin.staffAddGroups",
		"admin.povAddGroups",
		"admin.mpdAddGroups",
		"admin.licenseAddGroups",
		"admin.donoAddGroups",
		"admin.nhsAddGroups",

		"group.add.vipgarage",
        "group.add.commanager",
        "group.add.headadmin",
        "group.add.senioradmin",
        "group.add.administrator",
        "group.add.moderator",
        "group.add.trial",
        "group.add",

		"group.remove.vipgarage",
        "group.remove.commanager",
        "group.remove.headadmin",
        "group.remove.senioradmin",
        "group.remove.administrator",
        "group.remove.moderator",
        "group.remove.trial",
		"group.remove",
		
		"admin.whitelisted",
		"admin.tickets",
	},
	["commanager"] = {
	"admin.menu",
	"admin.warn",
	"admin.showwarn",
	"admin.ban",
	"admin.kick",
	"admin.nof10kick",
	"admin.revive",
	"admin.tp2player",
	"admin.summon",
	"admin.freeze",
	"admin.getgroups",
	"admin.spectate",
	"admin.screenshot",
	"admin.slap",
	"admin.givemoney",
	"admin.tp2waypoint",
	"admin.tp2coords",
	"admin.removewarn",
	"admin.spawnBmx",
	"admin.noclip",
	"staff.mode",
	"admin.idsabovehead",
	"vehicle.delete",
		
	"admin.staffAddGroups",
	"admin.povAddGroups",
	"admin.mpdAddGroups",
	"admin.licenseAddGroups",
	"admin.donoAddGroups",
	"admin.nhsAddGroups",

	"group.add.vipgarage",
	"group.add.headadmin",
	"group.add.senioradmin",
	"group.add.administrator",
	"group.add.moderator",
	"group.add.trial",
	"group.add",

	"group.remove.vipgarage",
	"group.remove.headadmin",
	"group.remove.senioradmin",
	"group.remove.administrator",
	"group.remove.moderator",
	"group.remove.trial",
	"group.remove",
	
	"admin.whitelisted",
	"admin.tickets",
	  },
	["headadmin"] = {
	"admin.menu",
    "admin.warn",
    "admin.showwarn",
    "admin.ban",
    "admin.kick",
    "admin.nof10kick",
    "admin.revive",
    "admin.tp2player",
    "admin.summon",
    "admin.freeze",
    "admin.spectate",
    "admin.screenshot",
    "admin.slap",
    "admin.tp2waypoint",
    "admin.tp2coords",
	"admin.removewarn",
	"admin.spawnBmx",
	"admin.noclip",
	"staff.mode",
	"admin.idsabovehead",
	"vehicle.delete",
			
	"admin.staffAddGroups",
	"admin.povAddGroups",
	"admin.mpdAddGroups",
	"admin.licenseAddGroups",
	"admin.donoAddGroups",
	"admin.nhsAddGroups",

	"group.add.vipgarage",
    "group.add",
	
	"admin.whitelisted",
	"admin.tickets",
  },
  ["senioradmin"] = {
	"admin.menu",
	"admin.warn",
	"admin.showwarn",
	"admin.ban",
	"admin.kick",
	"admin.nof10kick",
	"admin.revive",
	"admin.tp2player",
	"admin.summon",
	"admin.freeze",
	"admin.spectate",
	"admin.screenshot",
	"admin.slap",
	"admin.tp2waypoint",
	"admin.tp2coords",
	"admin.removewarn",
	"admin.spawnBmx",
	"admin.noclip",
	"staff.mode",
	"admin.idsabovehead",
	"vehicle.delete",
		
	"admin.staffAddGroups",
	"admin.povAddGroups",
	"admin.mpdAddGroups",
	"admin.donoAddGroups",
	"admin.nhsAddGroups",

	"group.add.vipgarage",
    "group.add",
	
	"admin.whitelisted",
	"admin.tickets",
  },
  ["administrator"] = {
	"admin.menu",
	"admin.warn",
	"admin.showwarn",
	"admin.ban",
	"admin.kick",
	"admin.nof10kick",
	"admin.revive",
	"admin.tp2player",
	"admin.summon",
	"admin.freeze",
	"admin.spectate",
	"admin.screenshot",
	"admin.slap",
	"admin.tp2waypoint",
	"admin.tp2coords",
		
	"admin.staffAddGroups",
	"admin.povAddGroups",
	"admin.mpdAddGroups",
	"admin.donoAddGroups",
	"admin.nhsAddGroups",

	"group.add.vipgarage",
    "group.add",

	"admin.whitelisted",
	"admin.tickets",
	"admin.spawnBmx",
	"staff.mode",
	"admin.idsabovehead",
	"vehicle.delete",
  },
  ["srmoderator"] = {
    "admin.menu",
    "admin.warn",
    "admin.showwarn",
    "admin.ban",
    "admin.kick",
    "admin.nof10kick",
    "admin.revive",
    "admin.tp2player",
    "admin.summon",
    "admin.freeze",
    "admin.screenshot",
    "admin.tp2waypoint",
    "admin.tp2coords",
		
	"admin.staffAddGroups",
	"admin.povAddGroups",
	"admin.mpdAddGroups",
	"admin.donoAddGroups",
	"admin.nhsAddGroups",

    "group.add",

    "admin.whitelisted",
    "admin.tickets",
    "admin.spawnBmx",
	"staff.mode",
	"admin.idsabovehead",
	"vehicle.delete",
    },
	["supportteam"] = {
		"admin.menu",
		"admin.warn",
		"admin.showwarn",
		"admin.ban",
		"admin.kick",
		"admin.nof10kick",
		"admin.revive",
		"admin.tp2player",
		"admin.summon",
		"admin.freeze",
		"admin.screenshot",
		"admin.tp2waypoint",
		"admin.tp2coords",
		"admin.staffAddGroups",
		"admin.povAddGroups",
		"admin.mpdAddGroups",
		"admin.donoAddGroups",
		"admin.nhsAddGroups",
		"group.add",
		"admin.whitelisted",
		"admin.tickets",
		"admin.spawnBmx",
		"staff.mode",
		"admin.idsabovehead",
		"vehicle.delete",
		},
  ["moderator"] = {
	"admin.menu",
	"admin.warn",
	"admin.showwarn",
	"admin.ban",
	"admin.kick",
	"admin.nof10kick",
	"admin.revive",
	"admin.tp2player",
	"admin.summon",
	"admin.freeze",
	"admin.screenshot",
	"admin.tp2waypoint",
	"admin.tp2coords",
		
	"admin.staffAddGroups",
	"admin.povAddGroups",
	"admin.mpdAddGroups",
	"admin.donoAddGroups",
	"admin.nhsAddGroups",
	"admin.spectate",

    "group.add",

	"admin.whitelisted",
	"admin.tickets",
	"admin.spawnBmx",
	"staff.mode",
	"admin.idsabovehead",
	"vehicle.delete",
  },
  ["trialstaff"] = {
    "admin.menu",
	"admin.warn",
	"admin.showwarn",
	"admin.kick",
	"admin.nof10kick",
	"admin.tp2player",
	"admin.summon",
	"admin.freeze",
	"admin.tp2coords",
	"admin.whitelisted",
	"admin.tickets",
	"admin.spawnBmx",
	"staff.mode",
	"admin.idsabovehead",
	"vehicle.delete",
  },]]

["dev"] = {
	"dev.menu", -- Dev Menu access
	"admin.givemoney", -- Founder
	"admin.spawnGun", -- Founder
	"admin.vehmenu", -- Car Dev
	"admin.menu",
	"admin.tickets",
    "admin.warn",
    "admin.showwarn",
    "admin.ban",
    "admin.kick",
    "admin.nof10kick",
    "admin.revive",
    "admin.tp2player",
    "admin.summon",
    "admin.freeze",
    "admin.spectate",
    "admin.slap",
    "admin.tp2waypoint",
    "admin.tp2coords",
	"admin.removewarn",
	"admin.spawntaxi",
	"admin.noclip",
	"admin.addcar",
	"admin.staffAddGroups",
	"admin.povAddGroups",
	"admin.mpdAddGroups",
	"admin.licenseAddGroups",
	"admin.donoAddGroups",
	"admin.nhsAddGroups",

-- Add Groups
	"group.add.opmanager",
	"group.add.staffmanager",
	"group.add.commanager",
	"group.add.headadmin",
	"group.add.senioradmin",
	"group.add.administrator",
	"group.add.srmoderator",
	"group.add.supportteam",
	"group.add.moderator",
	"group.add.trialstaff",
	"group.add.vip",
	"group.add",
-- Remove Groups
	"group.remove.staffmanager",
	"group.remove.commanager",
	"group.remove.headadmin",
	"group.add.vip",
	"group.remove.senioradmin",
	"group.remove.administrator",
	"group.remove.srmoderator",
	"group.remove.supportteam",
	"group.remove.moderator",
	"group.remove.trialstaff",
	"group.remove",

},
["founder"] = {
	"dev.menu", -- Dev Menu access
	"admin.givemoney", -- Founder
	"admin.spawnGun", -- Founder
	"admin.vehmenu", -- Car Dev
	"admin.menu",
	"admin.tickets",
    "admin.warn",
    "admin.showwarn",
    "admin.ban",
    "admin.kick",
    "admin.nof10kick",
    "admin.revive",
    "admin.tp2player",
    "admin.summon",
    "admin.freeze",
    "admin.spectate",
    "admin.slap",
    "admin.tp2waypoint",
    "admin.tp2coords",
	"admin.removewarn",
	"admin.spawntaxi",
	"admin.noclip",
	"admin.addcar",
	"admin.staffAddGroups",
	"admin.povAddGroups",
	"admin.mpdAddGroups",
	"admin.licenseAddGroups",
	"admin.donoAddGroups",
	"admin.nhsAddGroups",

-- Add Groups
	"group.add.opmanager",
	"group.add.staffmanager",
	"group.add.commanager",
	"group.add.headadmin",
	"group.add.senioradmin",
	"group.add.administrator",
	"group.add.srmoderator",
	"group.add.supportteam",
	"group.add.moderator",
	"group.add.trialstaff",
	"group.add",
-- Remove Groups
	"group.remove.staffmanager",
	"group.remove.commanager",
	"group.remove.headadmin",
	"group.remove.senioradmin",
	"group.remove.administrator",
	"group.remove.srmoderator",
	"group.remove.supportteam",
	"group.remove.moderator",
	"group.remove.trialstaff",
	"group.remove",
},
["opmanager"] = {
	"admin.menu",
	"admin.tickets",
    "admin.warn",
    "admin.showwarn",
    "admin.ban",
    "admin.kick",
    "admin.nof10kick",
    "admin.revive",
    "admin.tp2player",
    "admin.summon",
    "admin.freeze",
    "admin.spectate",
    "admin.slap",
    "admin.tp2waypoint",
    "admin.tp2coords",
	"admin.removewarn",
	"admin.spawntaxi",
	"admin.noclip",
	"admin.addcar",
	"admin.staffAddGroups",
	"admin.povAddGroups",
	"admin.mpdAddGroups",
	"admin.nhsAddGroups",

-- Add Groups
	"group.add.headadmin",
	"group.add.senioradmin",
	"group.add.administrator",
	"group.add.srmoderator",
	"group.add.supportteam",
	"group.add.moderator",
	"group.add.trialstaff",
	"group.add",
-- Remove Groups
	"group.remove.headadmin",
	"group.remove.senioradmin",
	"group.remove.administrator",
	"group.remove.srmoderator",
	"group.remove.supportteam",
	"group.remove.moderator",
	"group.remove.trialstaff",
	"group.remove",
},
["commanager"] = {
	"admin.menu",
	"admin.tickets",
    "admin.warn",
    "admin.showwarn",
    "admin.ban",
    "admin.kick",
    "admin.nof10kick",
    "admin.revive",
    "admin.tp2player",
    "admin.summon",
    "admin.freeze",
    "admin.spectate",
    "admin.slap",
    "admin.tp2waypoint",
    "admin.tp2coords",
	"admin.removewarn",
	"admin.spawntaxi",
	"admin.noclip",
	"admin.addcar",
	"admin.staffAddGroups",
	"admin.povAddGroups",
	"admin.mpdAddGroups",
	"admin.nhsAddGroups",

-- Add Groups
	"group.add.headadmin",
	"group.add.senioradmin",
	"group.add.administrator",
	"group.add.srmoderator",
	"group.add.supportteam",
	"group.add.moderator",
	"group.add.trialstaff",
	"group.add",
-- Remove Groups
	"group.remove.headadmin",
	"group.remove.senioradmin",
	"group.remove.administrator",
	"group.remove.srmoderator",
	"group.remove.supportteam",
	"group.remove.moderator",
	"group.remove.trialstaff",
	"group.remove",
},
["staffmanager"] = {
	"admin.menu",
	"admin.tickets",
    "admin.warn",
    "admin.showwarn",
    "admin.ban",
    "admin.kick",
    "admin.nof10kick",
    "admin.revive",
    "admin.tp2player",
    "admin.summon",
    "admin.freeze",
    "admin.spectate",
    "admin.slap",
    "admin.tp2waypoint",
    "admin.tp2coords",
	"admin.removewarn",
	"admin.spawntaxi",
	"admin.noclip",
	"admin.addcar",
	"admin.staffAddGroups",
	"admin.povAddGroups",
	"admin.mpdAddGroups",
	"admin.nhsAddGroups",

-- Add Groups
	"group.add.headadmin",
	"group.add.senioradmin",
	"group.add.administrator",
	"group.add.srmoderator",
	"group.add.supportteam",
	"group.add.moderator",
	"group.add.trialstaff",
	"group.add",
-- Remove Groups
	"group.remove.headadmin",
	"group.remove.senioradmin",
	"group.remove.administrator",
	"group.remove.srmoderator",
	"group.remove.supportteam",
	"group.remove.moderator",
	"group.remove.trialstaff",
	"group.remove",
},
["headadmin"] = {
	"admin.menu",
	"admin.tickets",
    "admin.warn",
    "admin.showwarn",
    "admin.ban",
    "admin.kick",
    "admin.nof10kick",
    "admin.revive",
    "admin.tp2player",
    "admin.summon",
    "admin.freeze",
    "admin.spectate",
    "admin.slap",
    "admin.tp2waypoint",
	"admin.removewarn",
	"admin.spawntaxi",
	"admin.noclip",
	"admin.povAddGroups",
	"admin.mpdAddGroups",
	"admin.nhsAddGroups",

-- Add Groups
	"group.add",
-- Remove Groups
	"group.remove",
},
["senioradmin"] = {
	"admin.menu",
	"admin.tickets",
    "admin.warn",
    "admin.showwarn",
    "admin.ban",
    "admin.kick",
    "admin.nof10kick",
    "admin.revive",
    "admin.tp2player",
    "admin.summon",
    "admin.freeze",
    "admin.spectate",
    "admin.slap",
    "admin.tp2waypoint",
	"admin.spawntaxi",
	"admin.noclip",
	"admin.povAddGroups",
	"admin.mpdAddGroups",
	"admin.nhsAddGroups",
-- Add Groups
	"group.add",
-- Remove Groups
	"group.remove",
},
["administrator"] = {
	"admin.menu",
	"admin.tickets",
    "admin.warn",
    "admin.showwarn",
    "admin.ban",
    "admin.kick",
    "admin.nof10kick",
    "admin.revive",
    "admin.tp2player",
    "admin.summon",
    "admin.freeze",
    "admin.spectate",
    "admin.slap",
    "admin.tp2waypoint",
	"admin.spawntaxi",
	"admin.noclip",
	"admin.povAddGroups",
	"admin.mpdAddGroups",
	"admin.nhsAddGroups",
-- Add Groups
	"group.add",
-- Remove Groups
	"group.remove",
},
["srmoderator"] = {
	"admin.menu",
	"admin.tickets",
    "admin.warn",
    "admin.showwarn",
    "admin.ban",
    "admin.kick",
    "admin.nof10kick",
    "admin.revive",
    "admin.tp2player",
    "admin.summon",
    "admin.freeze",
    "admin.spectate",
    "admin.slap",
    "admin.tp2waypoint",
	"admin.spawntaxi",
	"admin.povAddGroups",
	"admin.mpdAddGroups",
	"admin.nhsAddGroups",
-- Add Groups
	"group.add",
-- Remove Groups
	"group.remove",
},
["moderator"] = {
	"admin.menu",
	"admin.tickets",
    "admin.warn",
    "admin.showwarn",
    "admin.ban",
    "admin.kick",
    "admin.nof10kick",
    "admin.revive",
    "admin.tp2player",
    "admin.summon",
    "admin.freeze",
    "admin.tp2waypoint",
	"admin.spawntaxi",
},
["supportteam"] = {
	"admin.menu",
	"admin.tickets",
    "admin.warn",
    "admin.showwarn",
    "admin.ban",
    "admin.kick",
    "admin.nof10kick",
    "admin.tp2player",
    "admin.summon",
    "admin.tp2waypoint",
	"admin.spawntaxi",
},

["trialstaff"] = {
	"admin.menu",
	"admin.tickets",
    "admin.warn",
    "admin.showwarn",
    "admin.kick",
    "admin.nof10kick",
    "admin.tp2player",
    "admin.summon",
    "admin.tp2waypoint",
	"admin.spawntaxi",
},


  --[PD GROUPS]--
  ["Commissioner Clocked"] = {
    _config = { gtype = "job",
	  onjoin = function(player) vRPclient.setCop(player,{true}) end,
      onspawn = function(player) vRPclient.setCop(player,{true}) end,
	  onleave = function(player)
		local user_id = vRP.getUserId(player)
		ExecuteCommand("storeweapons")
		TriggerClientEvent("ORPINV:ClearWWheel", player)
		vRP.clearInventory(user_id)
		vRPclient.setCop(player,{false})
		TriggerClientEvent("DeleteBlipsALL", player)
	  end
	},
	"Chief.cloakroom",
    "police.pc",
    --"police.handcuff",
	"police.putinveh",
	"cop.glock",
    "police.getoutveh",
    "police.service",
	"police.drag",
	"police.easy_cuff",
	"commissioner.paycheck",
	"police.easy_fine",
	"police.easy_jail",
	"police.easy_unjail",
	"police.spikes",
	"police.menu",
    "police.check",
	"toggle.service",
	"police.freeze",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    --"police.jail",
    --"police.fine",
    "police.announce",
    --"-police.store_weapons",
    "police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"response.armor",
	"com.paycheck",
	"police.menu_interaction",
	"police.perms",
	"police.mission",
	"police.armoury",
	"cop.keycard",
	"police.smartsigns",
  },

  ["Commissioner"] = {
    "commissioner.clockon",
	"clockon.menu",
  },

  ["Deputy Commissioner Clocked"] = {
    _config = { gtype = "job",
	  onjoin = function(player) vRPclient.setCop(player,{true}) end,
      onspawn = function(player) vRPclient.setCop(player,{true}) end,
	  onleave = function(player)
		local user_id = vRP.getUserId(player)
		ExecuteCommand("storeweapons")
		TriggerClientEvent("ORPINV:ClearWWheel", player)
		vRP.clearInventory(user_id)
		vRPclient.setCop(player,{false})
		TriggerClientEvent("DeleteBlipsALL", player)
	  end
	},
	"Chief.cloakroom",
    "police.pc",
    --"police.handcuff",
    "police.putinveh",
	"police.getoutveh",
	"deputycommissioner.paycheck",
    "police.service",
	"police.drag",
	"police.easy_cuff",
	"police.easy_fine",
	"police.easy_jail",
	"police.easy_unjail",
	"police.spikes",
	"police.menu",
    "police.check",
	"toggle.service",
	"police.freeze",
    "police.wanted",
	"police.seize.weapons",
	"cop.glock",
    "police.seize.items",
    --"police.jail",
    --"police.fine",
    "police.announce",
    --"-police.store_weapons",
    "police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"response.armor",
	"depcom.paycheck",
	"police.menu_interaction",
	"police.perms",
	"police.mission",
	"police.armoury",
	"cop.keycard",
	"police.smartsigns",
  },

  ["Deputy Commissioner"] = {
    "depcommissioner.clockon",
	"clockon.menu",
  },

  ["Assistant Commissioner Clocked"] = {
    _config = { gtype = "job",
	  onjoin = function(player) vRPclient.setCop(player,{true}) end,
      onspawn = function(player) vRPclient.setCop(player,{true}) end,
	  onleave = function(player)
		local user_id = vRP.getUserId(player)
		ExecuteCommand("storeweapons")
		TriggerClientEvent("ORPINV:ClearWWheel", player)
		vRP.clearInventory(user_id)
		vRPclient.setCop(player,{false})
		TriggerClientEvent("DeleteBlipsALL", player)
	  end
	},
	"Chief.cloakroom",
    "police.pc",
    --"police.handcuff",
	"police.putinveh",
	"assistantcommissioner.paycheck",
    "police.getoutveh",
	"police.service",
	"cop.glock",
	"police.drag",
	"police.easy_cuff",
	"police.easy_fine",
	"police.easy_jail",
	"police.easy_unjail",
	"police.spikes",
	"police.menu",
    "police.check",
	"toggle.service",
	"police.freeze",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    --"police.jail",
    --"police.fine",
    "police.announce",
    --"-police.store_weapons",
    "police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"response.armor",
	"assistcom.paycheck",
	"police.menu_interaction",
	"police.perms",
	"police.mission",
	"police.armoury",
	"cop.keycard",
	"police.smartsigns",
  },

  ["Assistant Commissioner"] = {
    "asscommissioner.clockon",
	"clockon.menu",
  },

  ["Deputy Assistant Commissioner Clocked"] = {
    _config = { gtype = "job",
	  onjoin = function(player) vRPclient.setCop(player,{true}) end,
      onspawn = function(player) vRPclient.setCop(player,{true}) end,
	  onleave = function(player)
		local user_id = vRP.getUserId(player)
		ExecuteCommand("storeweapons")
		TriggerClientEvent("ORPINV:ClearWWheel", player)
		vRP.clearInventory(user_id)
		vRPclient.setCop(player,{false})
		TriggerClientEvent("DeleteBlipsALL", player)
	  end
	},
	"Chief.cloakroom",
    "police.pc",
    --"police.handcuff",
    "police.putinveh",
	"police.getoutveh",
	"assistantdeputycommissioner.paycheck",
    "police.service",
	"police.drag",
	"police.easy_cuff",
	"police.easy_fine",
	"police.easy_jail",
	"police.easy_unjail",
	"police.spikes",
	"police.menu",
    "police.check",
	"toggle.service",
	"cop.glock",
	"police.freeze",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    --"police.jail",
    --"police.fine",
    "police.announce",
    --"-police.store_weapons",
    "police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"response.armor",
	"depassist.paycheck",
	"police.menu_interaction",
	"police.perms",
	"police.mission",
	"police.armoury",
	"cop.keycard",
	"police.smartsigns",
  },

  ["Deputy Assistant Commissioner"] = {
    "depasscommissioner.clockon",
	"clockon.menu",
  },

  ["Commander Clocked"] = {
    _config = { gtype = "job",
	  onjoin = function(player) vRPclient.setCop(player,{true}) end,
      onspawn = function(player) vRPclient.setCop(player,{true}) end,
	  onleave = function(player)
		local user_id = vRP.getUserId(player)
		ExecuteCommand("storeweapons")
		TriggerClientEvent("ORPINV:ClearWWheel", player)
		vRP.clearInventory(user_id)
		vRPclient.setCop(player,{false})
		TriggerClientEvent("DeleteBlipsALL", player)
	  end
	},
	"Chief.cloakroom",
    "police.pc",
    --"police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.service",
	"police.drag",
	"commander.paycheck",
	"police.easy_cuff",
	"police.easy_fine",
	"police.easy_jail",
	"cop.glock",
	"police.easy_unjail",
	"police.spikes",
	"police.menu",
    "police.check",
	"toggle.service",
	"police.freeze",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    --"police.jail",
    --"police.fine",
    "police.announce",
    --"-police.store_weapons",
    "police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"response.armor",
	"com.paycheck",
	"police.menu_interaction",
	"police.perms",
	"police.mission",
	"police.armoury",
	"cop.keycard",
	"police.smartsigns",
  },

  ["Commander"] = {
    "commander.clockon",
	"clockon.menu",
  },

  ["Chief Superintendent Clocked"] = {
    _config = { gtype = "job",
	  onjoin = function(player) vRPclient.setCop(player,{true}) end,
      onspawn = function(player) vRPclient.setCop(player,{true}) end,
	  onleave = function(player)
		local user_id = vRP.getUserId(player)
		ExecuteCommand("storeweapons")
		TriggerClientEvent("ORPINV:ClearWWheel", player)
		vRP.clearInventory(user_id)
		vRPclient.setCop(player,{false})
		TriggerClientEvent("DeleteBlipsALL", player)
	  end
	},
	"Chief.cloakroom",
    "police.pc",
    --"police.handcuff",
	"police.putinveh",
	"chiefsuperintendent.paycheck",
    "police.getoutveh",
    "police.service",
	"police.drag",
	"police.easy_cuff",
	"police.easy_fine",
	"police.easy_jail",
	"police.easy_unjail",
	"police.spikes",
	"police.menu",
    "police.check",
	"toggle.service",
	"police.freeze",
    "police.wanted",
    "police.seize.weapons",
	"police.seize.items",
	"cop.glock",
    --"police.jail",
    --"police.fine",
    "police.announce",
    --"-police.store_weapons",
    "police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"response.armor",
	"chiefsupt.paycheck",
	"police.menu_interaction",
	"police.perms",
	"police.mission",
	"police.armoury",
	"cop.keycard",
	"police.smartsigns",
  },

  ["Chief Superintendent"] = {
    "chiefsupint.clockon",
	"clockon.menu",
  },

  ["Superintendent Clocked"] = {
    _config = { gtype = "job",
	  onjoin = function(player) vRPclient.setCop(player,{true}) end,
      onspawn = function(player) vRPclient.setCop(player,{true}) end,
	  onleave = function(player)
		local user_id = vRP.getUserId(player)
		ExecuteCommand("storeweapons")
		TriggerClientEvent("ORPINV:ClearWWheel", player)
		vRP.clearInventory(user_id)
		vRPclient.setCop(player,{false})
		TriggerClientEvent("DeleteBlipsALL", player)
	  end
	},
	"Chief.cloakroom",
    "police.pc",
    --"police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.service",
	"police.drag",
	"police.easy_cuff",
	"police.easy_fine",
	"police.easy_jail",
	"police.easy_unjail",
	"police.spikes",
	"police.menu",
    "police.check",
	"toggle.service",
	"police.freeze",
	"cop.glock",
	"police.wanted",
	"superintendent.paycheck",
    "police.seize.weapons",
    "police.seize.items",
    --"police.jail",
    --"police.fine",
    "police.announce",
    --"-police.store_weapons",
    "police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"response.armor",
	"supt.paycheck",
	"police.menu_interaction",
	"police.perms",
	"police.mission",
	"police.armoury",
	"cop.keycard",
	"police.smartsigns",
  },

  ["Superintendent"] = {
    "superint.clockon",
	"clockon.menu",
  },

  ["Chief Inspector Clocked"] = {
    _config = { gtype = "job",
	  onjoin = function(player) vRPclient.setCop(player,{true}) end,
      onspawn = function(player) vRPclient.setCop(player,{true}) end,
	  onleave = function(player)
		local user_id = vRP.getUserId(player)
		ExecuteCommand("storeweapons")
		TriggerClientEvent("ORPINV:ClearWWheel", player)
		vRP.clearInventory(user_id)
		vRPclient.setCop(player,{false})
		TriggerClientEvent("DeleteBlipsALL", player)
	  end
	},
	"Chief.cloakroom",
    "police.pc",
    --"police.handcuff",
    "police.putinveh",
    "police.getoutveh",
	"police.service",
	"chiefinspector.paycheck",
	"police.drag",
	"police.easy_cuff",
	"police.easy_fine",
	"police.easy_jail",
	"police.easy_unjail",
	"police.spikes",
	"police.menu",
	"cop.glock",
    "police.check",
	"toggle.service",
	"police.freeze",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    --"police.jail",
    --"police.fine",
    "police.announce",
    --"-police.store_weapons",
    "police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"response.armor",
	"chiefinspector.paycheck",
	"police.menu_interaction",
	"police.perms",
	"police.mission",
	"police.armoury",
	"cop.keycard",
	"police.smartsigns",
  },

  ["Chief Inspector"] = {
    "chiefinsp.clockon",
	"clockon.menu",
  },

  ["Inspector Clocked"] = {
    _config = { gtype = "job",
	  onjoin = function(player) vRPclient.setCop(player,{true}) end,
      onspawn = function(player) vRPclient.setCop(player,{true}) end,
	  onleave = function(player)
		local user_id = vRP.getUserId(player)
		ExecuteCommand("storeweapons")
		TriggerClientEvent("ORPINV:ClearWWheel", player)
		vRP.clearInventory(user_id)
		vRPclient.setCop(player,{false})
		TriggerClientEvent("DeleteBlipsALL", player)
	  end
	},
	"Chief.cloakroom",
    "police.pc",
    --"police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.service",
	"police.drag",
	"police.easy_cuff",
	"police.easy_fine",
	"police.easy_jail",
	"police.easy_unjail",
	"police.spikes",
	"inspector.paycheck",
	"police.menu",
    "police.check",
	"toggle.service",
	"police.freeze",
	"cop.glock",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    --"police.jail",
    --"police.fine",
    "police.announce",
    --"-police.store_weapons",
    "police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"response.armor",
	"inspector.paycheck",
	"police.menu_interaction",
	"police.perms",
	"police.mission",
	"police.armoury",
	"cop.keycard",
	"police.smartsigns",
  },

  ["Inspector"] = {
    "inspector.clockon",
	"clockon.menu",
  },

  ["Sergeant Clocked"] = {
    _config = { gtype = "job",
	  onjoin = function(player) vRPclient.setCop(player,{true}) end,
      onspawn = function(player) vRPclient.setCop(player,{true}) end,
	  onleave = function(player)
		local user_id = vRP.getUserId(player)
		ExecuteCommand("storeweapons")
		TriggerClientEvent("ORPINV:ClearWWheel", player)
		vRP.clearInventory(user_id)
		vRPclient.setCop(player,{false})
		TriggerClientEvent("DeleteBlipsALL", player)
	  end
	},
	"Chief.cloakroom",
    "police.pc",
    --"police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.service",
	"police.drag",
	"police.easy_cuff",
	"police.easy_fine",
	"police.easy_jail",
	"sergeant.paycheck",
	"police.easy_unjail",
	"cop.glock",
	"police.spikes",
	"police.menu",
    "police.check",
	"toggle.service",
	"police.freeze",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    --"police.jail",
    --"police.fine",
    "police.announce",
    --"-police.store_weapons",
    "police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"response.armor",
	"sergeant.paycheck",
	"police.menu_interaction",
	"police.perms",
	"police.mission",
	"police.armoury",
	"cop.keycard",
	"police.smartsigns",
  },

  ["Sergeant"] = {
    "sgt.clockon",
	"clockon.menu",
  },

  ["Special Police Constable Clocked"] = {
    _config = { gtype = "job",
	  onjoin = function(player) vRPclient.setCop(player,{true}) end,
      onspawn = function(player) vRPclient.setCop(player,{true}) end,
	  onleave = function(player)
		local user_id = vRP.getUserId(player)
		ExecuteCommand("storeweapons")
		TriggerClientEvent("ORPINV:ClearWWheel", player)
		vRP.clearInventory(user_id)
		vRPclient.setCop(player,{false})
		TriggerClientEvent("DeleteBlipsALL", player)
	  end
	},
	"Chief.cloakroom",
    "police.pc",
    --"police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.service",
	"police.drag",
	"police.easy_cuff",
	"police.easy_fine",
	"police.easy_jail",
	"police.easy_unjail",
	"cop.glock",
	"police.spikes",
	"police.menu",
    "police.check",
	"toggle.service",
	"police.freeze",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    --"police.jail",
    --"police.fine",
	"police.announce",
    --"-police.store_weapons",
    "police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"response.armor",
	"spc.paycheck",
	"police.menu_interaction",
	"police.perms",
	"police.mission",
	"police.armoury",
	"cop.keycard",
	"police.smartsigns",
  },

  ["Special Police Constable"] = {
    "specialpc.clockon",
	"clockon.menu",
  },

  ["Senior Police Constable Clocked"] = {
    _config = { gtype = "job",
	  onjoin = function(player) vRPclient.setCop(player,{true}) end,
      onspawn = function(player) vRPclient.setCop(player,{true}) end,
	  onleave = function(player)
		local user_id = vRP.getUserId(player)
		ExecuteCommand("storeweapons")
		TriggerClientEvent("ORPINV:ClearWWheel", player)
		vRP.clearInventory(user_id)
		vRPclient.setCop(player,{false})
		TriggerClientEvent("DeleteBlipsALL", player)
	  end
	},
	"Chief.cloakroom",
    "police.pc",
    --"police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.service",
	"police.drag",
	"police.easy_cuff",
	"police.easy_fine",
	"police.easy_jail",
	"police.easy_unjail",
	"police.spikes",
	"police.menu",
    "police.check",
	"toggle.service",
	"police.freeze",
	"police.wanted",
	"cop.glock",
    "police.seize.weapons",
    "police.seize.items",
    --"police.jail",
    --"police.fine",
	"police.announce",
	"spc.paycheck",
    --"-police.store_weapons",
    "police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"response.armor",
	"seniorpc.paycheck",
	"police.menu_interaction",
	"police.perms",
	"police.mission",
	"police.armoury",
	"cop.keycard",
	"police.smartsigns",
  },

  ["Senior Police Constable"] = {
    "srpc.clockon",
	"clockon.menu",
  },

  ["Police Constable Clocked"] = {
    _config = { gtype = "job",
	  onjoin = function(player) vRPclient.setCop(player,{true}) end,
      onspawn = function(player) vRPclient.setCop(player,{true}) end,
	  onleave = function(player)
		local user_id = vRP.getUserId(player)
		ExecuteCommand("storeweapons")
		TriggerClientEvent("ORPINV:ClearWWheel", player)
		vRP.clearInventory(user_id)
		vRPclient.setCop(player,{false})
		TriggerClientEvent("DeleteBlipsALL", player)
	  end
	},
	"Chief.cloakroom",
    "police.pc",
    --"police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.service",
	"police.drag",
	"police.easy_cuff",
	"police.easy_fine",
	"police.easy_jail",
	"police.easy_unjail",
	"police.spikes",
	"police.menu",
    "police.check",
	"toggle.service",
	"police.freeze",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    --"police.jail",
    --"police.fine",
    "police.announce",
    --"-police.store_weapons",
    "police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"cop.glock",
	"response.armor",
	"policeconstable.paycheck",
	"police.menu_interaction",
	"police.perms",
	"police.mission",
	"police.armoury",
	"cop.keycard",
	"police.smartsigns",
  },

  ["Police Constable"] = {
    "pc.clockon",
	"clockon.menu",
  },

  ["PCSO Clocked"] = {
    _config = { gtype = "job",
	  onjoin = function(player) vRPclient.setCop(player,{true}) end,
	  onspawn = function(player) vRPclient.setCop(player,{true}) end,
	  onleave = function(player)
		local user_id = vRP.getUserId(player)
		TriggerClientEvent("ORPINV:ClearWWheel", player)
		vRP.clearInventory(user_id)
		vRPclient.setCop(player,{false})
		TriggerClientEvent("DeleteBlipsALL", player)
		TriggerClientEvent("VRPGUNSHOPS:givearmour", player, 0)
	  end
	},
	"Chief.cloakroom",
    "police.pc",
    --"police.handcuff",
    "police.putinveh",
    "police.getoutveh",
    "police.service",
	"police.drag",
	"police.easy_cuff",
	"police.easy_fine",
	"police.easy_jail",
	"police.easy_unjail",
	"police.spikes",
	"police.menu",
    "police.check",
	"toggle.service",
	"police.freeze",
    "police.wanted",
    "police.seize.weapons",
    "police.seize.items",
    --"police.jail",
    --"police.fine",
    "police.announce",
    --"-police.store_weapons",
    "police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
	"police.vehicle",
	"police.loadshop",
	"emergency.market",
	"emergency.revive",
	"emergency.shop",
	"cop.whitelisted",
	"cop.glock",
	"pcso.armor",
	"pcso.paycheck",
	"police.menu_interaction",
	"police.perms",
	"police.mission",
	"police.armoury",
	"cop.keycard",
	"police.smartsigns",
  },

  ["PCSO"] = {
    "pcso.clockon",
	"clockon.menu",
  },

  ["SCO-19"] = {
    "sco.armoury",
  },

    ["VIP"] = {
	"vip.perm",
  	},
	
	  ["Grind"] = {
		"grind.perm",
		  },

	  ["staffon"] = {
		"staffon.perm",
	  },
	  ["Rebel"] = {
		"rebel.guns",
	  },
	  ["Gang"] = {
		"gang.guns",
	  },
	  ["d"] = {
		"high.roller",
	  },

	  ["Garbage Job"] = {
		"garbage.job"
	  },
	
	  ["Weed"] = {
		"weed.job"
	  },
	  ["Diamond"] = {
		"diamond.job"
	  },
	  ["Heroin"] = {
		"heroin.job",
	  },
	  ["LSD"] = {
		"lsd.job"
	  },
	  ["LiteCoin"] = {
		"LiteCoin.job"
	  },
	  ["BitCoin"] = {
		"Bitcoin.job"
	  },
	  ["pov"] = {
		"pov.list"
	  },
	  ["TutorialDone"] = {
	  },
}

cfg.users = {
  }
-- group selectors
-- _config
--- x,y,z, blipid, blipcolor, permissions (optional)

cfg.selectors = {

  
}

return cfg
