
local cfg = {}


cfg.groups = {
	["dev"] = {
        "dev.menu",
        "dev.spawncar",
        "dev.spawnweapon",
        "dev.deletecar",
        "dev.fixcar",
		"dev.givemoney",
		"dev.tp2coords",
	    "dev.getcoords",
		"cardev.menu",
		"chat.announce",
		"admin.addcar",
		"admin.spawnGun",
        "admin.menu",
        "admin.warn",
		"admin.vehmenu",
        "admin.showwarn",
        "admin.ban",
		"admin.unban",
        "admin.kick",
        "admin.revive",
        "admin.tp2player",
        "admin.summon",
        "admin.freeze",
        "admin.getgroups",
        "admin.spectate",
        "admin.screenshot",
        "admin.slap",
        "admin.givemoney",
        "admin.tp2waypoint",
        "admin.tp2coords",
		"admin.removewarn",
		"admin.spawnBmx",
		"admin.idsabovehead",
		"admin.noclip",
		"admin.OpenMenu",
			
		"admin.staffAddGroups",
		"admin.povAddGroups",
		"admin.mpdAddGroups",
		"admin.licenseAddGroups",
		"admin.donoAddGroups",

		"group.add.vip",
        "group.add.founder",
        "group.add.operationsmanager",
        "group.add.staffmanager",
        "group.add.commanager",
        "group.add.headadmin",
        "group.add.senioradmin",
        "group.add.administrator",
        "group.add.srmoderator",
        "group.add.moderator",
        "group.add.supportteam",
        "group.add.trial",
		"group.add.pov",
        "group.add",

		"group.remove.vip",
        "group.remove.founder",
        "group.remove.operationsmanager",
        "group.remove.staffmanager",
        "group.remove.commanager",
        "group.remove.headadmin",
        "group.remove.senioradmin",
        "group.remove.administrator",
        "group.remove.srmoderator",
        "group.remove.moderator",
        "group.remove.supportteam",
        "group.remove.trial",
		"group.remove.pov",
		"group.remove",
		
		"admin.whitelisted",
		"admin.tickets",
	},
	["Director"] = {
		"dev.menu",
        "dev.spawncar",
        "dev.spawnweapon",
        "dev.deletecar",
        "dev.fixcar",
		"dev.givemoney",
		"dev.tp2coords",
	    "dev.getcoords",
		"cardev.menu",
		"chat.announce",
		
		"admin.menu",
        "admin.warn",
        "admin.showwarn",
        "admin.ban",
		"admin.unban",
        "admin.kick",
        "admin.revive",
        "admin.tp2player",
        "admin.summon",
        "admin.freeze",
        "admin.getgroups",
        "admin.spectate",
        "admin.screenshot",
        "admin.slap",
        "admin.givemoney",
        "admin.tp2waypoint",
        "admin.tp2coords",
		"admin.removewarn",
		"admin.spawnBmx",
		"admin.noclip",
    	"staff.mode",
		"admin.vehmenu",
		"admin.spawnGun",
		"admin.addcar",
		"admin.idsabovehead",
		"admin.smartsigns",
		"admin.staffAddGroups",
		"admin.povAddGroups",
		"admin.mpdAddGroups",
		"admin.licenseAddGroups",
		"admin.donoAddGroups",
		"admin.nhsAddGroups",
		"admin.OpenMenu",

		"group.add.vip",
        "group.add.founder",
        "group.add.operationsmanager",
        "group.add.staffmanager",
        "group.add.commanager",
        "group.add.headadmin",
        "group.add.senioradmin",
        "group.add.administrator",
        "group.add.srmoderator",
        "group.add.moderator",
        "group.add.supportteam",
        "group.add.trial",
		"group.add.pov",
        "group.add",

		"group.remove.vip",
        "group.remove.founder",
        "group.remove.operationsmanager",
        "group.remove.staffmanager",
        "group.remove.commanager",
        "group.remove.headadmin",
        "group.remove.senioradmin",
        "group.remove.administrator",
        "group.remove.srmoderator",
        "group.remove.moderator",
        "group.remove.supportteam",
        "group.remove.trial",
		"group.remove.pov",
		"group.remove",
		
		"admin.whitelisted",
		"admin.tickets",
		
		"vehicle.delete",
		"chat.announce",
		"cardev.menu",
	},
	["founder"] = {
		
		"admin.menu",
        "admin.warn",
        "admin.showwarn",
        "admin.ban",
		"admin.unban",
        "admin.kick",
        "admin.revive",
        "admin.tp2player",
        "admin.summon",
        "admin.freeze",
        "admin.getgroups",
        "admin.spectate",
        "admin.screenshot",
        "admin.slap",
        "admin.givemoney",
        "admin.tp2waypoint",
        "admin.tp2coords",
		"admin.removewarn",
		"admin.spawnBmx",
		"admin.noclip",
    	"staff.mode",
		"admin.vehmenu",
		"admin.spawnGun",
		"admin.addcar",
		"admin.idsabovehead",
		"admin.smartsigns",
		"admin.staffAddGroups",
		"admin.povAddGroups",
		"admin.mpdAddGroups",
		"admin.licenseAddGroups",
		"admin.donoAddGroups",
		"admin.nhsAddGroups",

		"admin.OpenMenu",
		"group.add.vip",
        "group.add.founder",
        "group.add.operationsmanager",
        "group.add.staffmanager",
        "group.add.commanager",
        "group.add.headadmin",
        "group.add.senioradmin",
        "group.add.administrator",
        "group.add.srmoderator",
        "group.add.moderator",
        "group.add.supportteam",
        "group.add.trial",
		"group.add.pov",
        "group.add",

		"group.remove.vip",
        "group.remove.founder",
        "group.remove.operationsmanager",
        "group.remove.staffmanager",
        "group.remove.commanager",
        "group.remove.headadmin",
        "group.remove.senioradmin",
        "group.remove.administrator",
        "group.remove.srmoderator",
        "group.remove.moderator",
        "group.remove.supportteam",
        "group.remove.trial",
		"group.remove.pov",
		"group.remove",
		
		"admin.whitelisted",
		"admin.tickets",
		
		"vehicle.delete",
		"chat.announce",
		"cardev.menu",
	},
	["director"] = {
		
		"admin.menu",
        "admin.warn",
        "admin.showwarn",
        "admin.ban",
		"admin.unban",
        "admin.kick",
        "admin.revive",
        "admin.tp2player",
        "admin.summon",
        "admin.freeze",
        "admin.getgroups",
        "admin.spectate",
        "admin.screenshot",
        "admin.slap",
        "admin.givemoney",
        "admin.tp2waypoint",
        "admin.tp2coords",
		"admin.removewarn",
		"admin.spawnBmx",
		"admin.noclip",
    	"staff.mode",
		"admin.vehmenu",
		"admin.spawnGun",
		"admin.addcar",
		"admin.idsabovehead",
		"admin.smartsigns",
		"admin.staffAddGroups",
		"admin.povAddGroups",
		"admin.mpdAddGroups",
		"admin.licenseAddGroups",
		"admin.donoAddGroups",
		"admin.nhsAddGroups",

		"admin.OpenMenu",
		"group.add.vip",
        "group.add.founder",
        "group.add.operationsmanager",
        "group.add.staffmanager",
        "group.add.commanager",
        "group.add.headadmin",
        "group.add.senioradmin",
        "group.add.administrator",
        "group.add.srmoderator",
        "group.add.moderator",
        "group.add.supportteam",
        "group.add.trial",
		"group.add.pov",
        "group.add",

		"group.remove.vip",
        "group.remove.founder",
        "group.remove.operationsmanager",
        "group.remove.staffmanager",
        "group.remove.commanager",
        "group.remove.headadmin",
        "group.remove.senioradmin",
        "group.remove.administrator",
        "group.remove.srmoderator",
        "group.remove.moderator",
        "group.remove.supportteam",
        "group.remove.trial",
		"group.remove.pov",
		"group.remove",
		
		"admin.whitelisted",
		"admin.tickets",
		
		"vehicle.delete",
		"chat.announce",
		"cardev.menu",
	},
	["operationsmanager"] = {
        "dev.menu",
        "dev.spawncar",
        "dev.spawnweapon",
        "dev.deletecar",
        "dev.fixcar",
		"dev.givemoney",
		"dev.tp2coords",
	    "dev.getcoords",
		"admin.special",
		"cardev.menu",
		"chat.announce",
		"admin.OpenMenu",

		"admin.addcar",
		"admin.spawnGun",
        "admin.menu",
        "admin.warn",
		"admin.vehmenu",
        "admin.showwarn",
        "admin.ban",
		"admin.unban",
        "admin.kick",
        "admin.revive",
        "admin.tp2player",
        "admin.summon",
        "admin.freeze",
        "admin.getgroups",
        "admin.spectate",
        "admin.screenshot",
        "admin.slap",
        "admin.givemoney",
        "admin.tp2waypoint",
        "admin.tp2coords",
		"admin.removewarn",
		"admin.spawnBmx",
		"admin.idsabovehead",
		"admin.noclip",
		
			
		"admin.staffAddGroups",
		"admin.povAddGroups",
		"admin.mpdAddGroups",
		"admin.licenseAddGroups",
		"admin.donoAddGroups",

		"group.add.vip",
        "group.add.staffmanager",
        "group.add.commanager",
        "group.add.headadmin",
        "group.add.senioradmin",
        "group.add.administrator",
        "group.add.srmoderator",
        "group.add.moderator",
        "group.add.supportteam",
        "group.add.trial",
		"group.add.pov",
        "group.add",

		"group.remove.vip",
        "group.remove.staffmanager",
        "group.remove.commanager",
        "group.remove.headadmin",
        "group.remove.senioradmin",
        "group.remove.administrator",
        "group.remove.srmoderator",
        "group.remove.moderator",
        "group.remove.supportteam",
        "group.remove.trial",
		"group.remove.pov",
		"group.remove",
		
		"admin.whitelisted",
		"admin.tickets",
	},
	["staffmanager"] = {
		"dev.menu",
        "dev.spawncar",
        "dev.deletecar",
        "dev.fixcar",
		"dev.tp2coords",
	    "dev.getcoords",
		"admin.vehmenu",
		"admin.special",
		"admin.OpenMenu",
		"admin.menu",
        "admin.warn",
        "admin.showwarn",
        "admin.ban",
		"admin.unban",
        "admin.kick",
        "admin.revive",
        "admin.tp2player",
        "admin.summon",
        "admin.freeze",
        "admin.getgroups",
        "admin.spectate",
		"admin.addcar",
        "admin.screenshot",
        "admin.slap",
        "admin.tp2waypoint",
        "admin.tp2coords",
		"admin.removewarn",
		"admin.spawnBmx",
		"admin.noclip",
    	"staff.mode",
		"admin.idsabovehead",
		"vehicle.delete",
		"cardev.menu",
		"admin.staffAddGroups",
		"admin.povAddGroups",
		"admin.mpdAddGroups",
		"admin.nhsAddGroups",
		"group.add.vip",
        "group.add.commanager",
        "group.add.headadmin",
        "group.add.senioradmin",
        "group.add.administrator",
        "group.add.srmoderator",
        "group.add.moderator",
        "group.add.supportteam",
        "group.add.trial",
		"group.add.pov",
        "group.add",

		"group.remove.vip",
        "group.remove.commanager",
        "group.remove.headadmin",
        "group.remove.senioradmin",
        "group.remove.administrator",
        "group.remove.srmoderator",
        "group.remove.moderator",
        "group.remove.supportteam",
        "group.remove.trial",
		"group.remove.pov",
		"group.remove",
		
		"admin.whitelisted",
		"admin.tickets",
		"chat.announce",
	},
	["commanager"] = {
		
		"admin.menu",
		"admin.warn",
		"admin.showwarn",
		"admin.ban",
		"admin.unban",
		"admin.kick",
		"admin.revive",
		"admin.tp2player",
		"admin.summon",
		"admin.addcar",
		"admin.freeze",
		"admin.getgroups",
		"admin.spectate",
		"admin.screenshot",
		"admin.slap",
		"admin.givemoney",
		"admin.tp2waypoint",
		"admin.tp2coords",
		"admin.removewarn",
		"admin.spawnBmx",
		"admin.noclip",
		"staff.mode",
		"admin.idsabovehead",
		"vehicle.delete",
		"admin.staffAddGroups",
		"admin.povAddGroups",
		"admin.mpdAddGroups",
		"admin.nhsAddGroups",
		"admin.OpenMenu",
        "group.add.headadmin",
        "group.add.senioradmin",
        "group.add.administrator",
        "group.add.srmoderator",
        "group.add.moderator",
        "group.add.supportteam",
        "group.add.trial",
		"group.add.pov",
        "group.add",

        "group.remove.headadmin",
        "group.remove.senioradmin",
        "group.remove.administrator",
        "group.remove.srmoderator",
        "group.remove.moderator",
        "group.remove.supportteam",
        "group.remove.trial",
		"group.remove.pov",
		"group.remove",
		
		"admin.whitelisted",
		"admin.tickets",
		"chat.announce",
	  },
	["headadmin"] = {
		
		"admin.menu",
		"admin.warn",
		"admin.showwarn",
		"admin.ban",
		"admin.unban",
		"admin.kick",
		"admin.revive",
		"admin.tp2player",
		"admin.summon",
		"admin.freeze",
		"admin.spectate",
		"admin.screenshot",
		"admin.slap",
		"admin.tp2waypoint",
		"admin.tp2coords",
		"admin.removewarn",
		"admin.spawnBmx",
		"admin.noclip",
		"staff.mode",
		"admin.idsabovehead",
		"vehicle.delete",
		"admin.staffAddGroups",
		"admin.povAddGroups",
		"admin.mpdAddGroups",
		"admin.nhsAddGroups",
		"admin.donoAddGroups",
		"admin.OpenMenu",
		
        "group.add.senioradmin",
        "group.add.administrator",
        "group.add.srmoderator",
        "group.add.moderator",
        "group.add.supportteam",
        "group.add.trial",
		"group.add.pov",
        "group.add",

        "group.remove.senioradmin",
        "group.remove.administrator",
        "group.remove.srmoderator",
        "group.remove.moderator",
        "group.remove.supportteam",
        "group.remove.trial",
		"group.remove.pov",
		"group.remove",
		
		
		"admin.whitelisted",
		"admin.tickets",
		"chat.announce",
  },
  ["senioradmin"] = {
	
		"admin.menu",
		"admin.warn",
		"admin.showwarn",
		"admin.ban",
		"admin.unban",
		"admin.kick",
		"admin.revive",
		"admin.tp2player",
		"admin.summon",
		"admin.freeze",
		"admin.spectate",
		"admin.screenshot",
		"admin.slap",
		"admin.tp2waypoint",
		"admin.tp2coords",
		"admin.removewarn",
		"admin.spawnBmx",
		"admin.noclip",
		"staff.mode",
		"admin.idsabovehead",
		"vehicle.delete",
		"admin.OpenMenu",
		"admin.whitelisted",
		"admin.tickets",
  },
  ["administrator"] = {
	
		"admin.menu",
		"admin.warn",
		"admin.showwarn",
		"admin.ban",
		"admin.unban",
		"admin.kick",
		"admin.revive",
		"admin.tp2player",
		"admin.summon",
		"admin.freeze",
		"admin.spectate",
		"admin.screenshot",
		"admin.slap",
		"admin.tp2waypoint",
		"admin.tp2coords",
		"admin.noclip",
		"admin.OpenMenu",
		"admin.whitelisted",
		"admin.tickets",
		"admin.spawnBmx",
		"staff.mode",
		"admin.idsabovehead",
		"vehicle.delete",
  },
  ["srmoderator"] = {
	
		"admin.menu",
		"admin.warn",
		"admin.showwarn",
		"admin.ban",
		"admin.unban",
		"admin.kick",
		"admin.revive",
		"admin.tp2player",
		"admin.summon",
		"admin.freeze",
		"admin.screenshot",
		"admin.spectate",
		"admin.OpenMenu",
		"admin.whitelisted",
		"admin.tickets",
		"admin.spawnBmx",
		"staff.mode",
		"admin.idsabovehead",
		"vehicle.delete",
    },
  ["moderator"] = {
	
		"admin.menu",
		"admin.warn",
		"admin.showwarn",
		"admin.ban",
		"admin.kick",
		"admin.revive",
		"admin.tp2player",
		"admin.summon",
		"admin.freeze",
		"admin.screenshot",
		"admin.spectate",
		"admin.OpenMenu",
		"admin.whitelisted",
		"admin.tickets",
		"admin.spawnBmx",
		"staff.mode",
		"admin.idsabovehead",
		"vehicle.delete",
		
  },
  ["supportteam"] = {
		"admin.menu",
		"admin.warn",
		"admin.showwarn",
		"admin.kick",
		"admin.spectate",
		"admin.tp2player",
		"admin.summon",
		"admin.freeze",
		"admin.whitelisted",
		"admin.tickets",
		"admin.spawnBmx",
		"staff.mode",
		"admin.idsabovehead",
		"vehicle.delete",
		"admin.ban",
		"admin.OpenMenu",
  },
  ["trialstaff"] = {
		"admin.menu",
		"admin.warn",
		"admin.showwarn",
		"admin.kick",
		"admin.tp2player",
		"admin.summon",
		"admin.freeze",
		"admin.whitelisted",
		"admin.tickets",
		"admin.spawnBmx",
		"staff.mode",
		"admin.idsabovehead",
		"vehicle.delete",
		"admin.OpenMenu",
  },
  ["cardev"] = {
	"cardev.menu",
},
["TutorialCompleted"] = {
	"TutorialCompleted",
},
     -- ["god"] = {
    -- "admin.god" -- reset survivals/health periodically
  -- },

  -- the group user is auto added to all logged players
  ["user"] = {
    "player.phone",
    "player.calladmin",
	"player.fix_haircut",
	"player.check",
	--"mugger.mug",
    "police.askid",
    "police.store_weapons",
	"player.skip_coma",
	"player.store_money",
	"player.check",
	"player.loot",
	"player.player_menu",
	"player.userlist",
    "police.seizable",	-- can be seized
	"user.paycheck"
  },

  -- [Donate]
  ["diamond"] = {
	"vip.guns",
  },
  ["VIP"] = {
	"vip.guns",
  },
  ["warrior"] = {
	"vip.guns",
  },
  ["soldier"] = {
	"vip.guns",
  },
  ["elite"] = {
	"vip.guns",
  },
  ["Redeemed"] = {
	"",
  },
  ["GANGWHITELIST"] = {
	"vip.guns",
  },
  

  -- [Licenses]
  ["Rebel"] = {
	"rebel.guns",
  },
  ["AdvancedRebel"] = {
	"advancedebel.guns",
  },
  ["Gang"] = {
	"gang.guns",
  },
  ["Scrap Job"] = {
	"scrap.job"
  },
  ["Cocaine"] = {
	"cocaine.job"
  },
  ["Weed"] = {
	"weed.job"
  },
  ["Heroin"] = {
	"heroin.job",
  },
  ["Iron"] = {
	"iron.job",
  },
  ["LSD"] = { 
	"lsd.job"
  },
  ["Diamond"] = {
	"diamond.job"
  },
  ["HighRoller"] = {
  },

  ["pov"] = {
	"pov.list"
  },

	["Police"] = {
		"pd.clockon",
		"cop.keycard",
	},

	["pdlargearms"] = {
		"pd.armourylarge",
	},
	-- [PD Groups]
	["Special Constable"] = {
		"specialconstable.pd",
		"police.armoury",
		"cop.keycard",
		"police.group",
		"police.call",
		"pd.armory",
		"Officer.cloakroom",
		"highway.cloakroom",
		"police.pc",
		--"police.handcuff",
		"police.putinveh",
		"police.getoutveh",
		"cop.keycard",
		"police.drag",
		"police.easy_cuff",
		"police.easy_fine",
		"police.easy_jail",
		"police.easy_unjail",
		"police.spikes",
		"police.menu",
		"police.check",
		"toggle.service",
		"police.freeze",
		"police.service",
		"police.wanted",
		"police.seize.weapons",
		"police.seize.items",
		--"police.jail",
		--"police.fine",
		"police.announce",
	-- "-police.store_weapons",
		"-police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
		"police.vehicle",
		"police.loadshop",
		"cop.whitelisted",
		"emergency.market",
		"emergency.revive",
		"emergency.shop",
		--"player.list",
		"police.paycheck",
		"police.mission",
		"player.blips",
		"police.menu_interaction",
		"police.maxarmour"
	},
	["Commissioner"] = {
		"commissioner.pd",
		"police.armoury",
		"cop.keycard",
		"police.group",
		"police.call",
		"pd.armory",
		"Officer.cloakroom",
		"highway.cloakroom",
		"police.pc",
		--"police.handcuff",
		"police.putinveh",
		"police.getoutveh",
		"cop.keycard",
		"police.drag",
		"police.easy_cuff",
		"police.easy_fine",
		"police.easy_jail",
		"police.easy_unjail",
		"police.spikes",
		"police.menu",
		"police.check",
		"toggle.service",
		"police.freeze",
		"police.service",
		"police.wanted",
		"police.seize.weapons",
		"police.seize.items",
		--"police.jail",
		--"police.fine",
		"police.announce",
	-- "-police.store_weapons",
		"-police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
		"police.vehicle",
		"police.loadshop",
		"cop.whitelisted",
		"emergency.market",
		"emergency.revive",
		"emergency.shop",
		--"player.list",
		"police.paycheck",
		"police.mission",
		"player.blips",
		"police.menu_interaction",
		"police.maxarmour"
	},
	["Deputy Commissioner"] = {
		"police.maxarmour",
		"deputycommissioner.pd",
		"police.armoury",
		"cop.keycard",
		"police.group",
		"police.call",
		"pd.armory",
		"Officer.cloakroom",
		"highway.cloakroom",
		"police.pc",
		--"police.handcuff",
		"police.putinveh",
		"police.getoutveh",
		"cop.keycard",
		"police.drag",
		"police.easy_cuff",
		"police.easy_fine",
		"police.easy_jail",
		"police.easy_unjail",
		"police.spikes",
		"police.menu",
		"police.check",
		"toggle.service",
		"police.freeze",
		"police.service",
		"police.wanted",
		"police.seize.weapons",
		"police.seize.items",
		--"police.jail",
		--"police.fine",
		"police.announce",
	-- "-police.store_weapons",
		"-police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
		"police.vehicle",
		"police.loadshop",
		"cop.whitelisted",
		"emergency.market",
		"emergency.revive",
		"emergency.shop",
		--"player.list",
		"police.paycheck",
		"police.mission",
		"player.blips",
		"police.menu_interaction"
	},
	["Assistant Commissioner"] = {
		"police.maxarmour",
		"deputycommissioner.pd",
		"police.armoury",
		"cop.keycard",
		"police.group",
		"police.call",
		"pd.armory",
		"Officer.cloakroom",
		"highway.cloakroom",
		"police.pc",
		--"police.handcuff",
		"police.putinveh",
		"police.getoutveh",
		"cop.keycard",
		"police.drag",
		"police.easy_cuff",
		"police.easy_fine",
		"police.easy_jail",
		"police.easy_unjail",
		"police.spikes",
		"police.menu",
		"police.check",
		"toggle.service",
		"police.freeze",
		"police.service",
		"police.wanted",
		"police.seize.weapons",
		"police.seize.items",
		--"police.jail",
		--"police.fine",
		"police.announce",
	-- "-police.store_weapons",
		"-police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
		"police.vehicle",
		"police.loadshop",
		"cop.whitelisted",
		"emergency.market",
		"emergency.revive",
		"emergency.shop",
		--"player.list",
		"police.paycheck",
		"police.mission",
		"player.blips",
		"police.menu_interaction"
	},
	["Deputy Assistant Commissioner"] = {
		"police.maxarmour",
		"deputyassistantcommissioner.pd",
		"police.armoury",
		"cop.keycard",
		"police.group",
		"police.call",
		"pd.armory",
		"Officer.cloakroom",
		"highway.cloakroom",
		"police.pc",
		--"police.handcuff",
		"police.putinveh",
		"police.getoutveh",
		"cop.keycard",
		"police.drag",
		"police.easy_cuff",
		"police.easy_fine",
		"police.easy_jail",
		"police.easy_unjail",
		"police.spikes",
		"police.menu",
		"police.check",
		"toggle.service",
		"police.freeze",
		"police.service",
		"police.wanted",
		"police.seize.weapons",
		"police.seize.items",
		--"police.jail",
		--"police.fine",
		"police.announce",
	-- "-police.store_weapons",
		"-police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
		"police.vehicle",
		"police.loadshop",
		"cop.whitelisted",
		"emergency.market",
		"emergency.revive",
		"emergency.shop",
		--"player.list",
		"police.paycheck",
		"police.mission",
		"player.blips",
		"police.menu_interaction"
	},
	["Commander"] = {
		"police.maxarmour",
		"commander.pd",
		"police.armoury",
		"cop.keycard",
		"police.group",
		"police.call",
		"pd.armory",
		"Officer.cloakroom",
		"highway.cloakroom",
		"police.pc",
		--"police.handcuff",
		"police.putinveh",
		"police.getoutveh",
		"cop.keycard",
		"police.drag",
		"police.easy_cuff",
		"police.easy_fine",
		"police.easy_jail",
		"police.easy_unjail",
		"police.spikes",
		"police.menu",
		"police.check",
		"toggle.service",
		"police.freeze",
		"police.service",
		"police.wanted",
		"police.seize.weapons",
		"police.seize.items",
		--"police.jail",
		--"police.fine",
		"police.announce",
	-- "-police.store_weapons",
		"-police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
		"police.vehicle",
		"police.loadshop",
		"cop.whitelisted",
		"emergency.market",
		"emergency.revive",
		"emergency.shop",
		--"player.list",
		"police.paycheck",
		"police.mission",
		"player.blips",
		"police.menu_interaction"
	},
	["Chief Superintendent"] = {
		"police.maxarmour",
		"chiefsuperintendent.pd",
		"police.armoury",
		"cop.keycard",
		"police.group",
		"police.call",
		"pd.armory",
		"Officer.cloakroom",
		"highway.cloakroom",
		"police.pc",
		--"police.handcuff",
		"police.putinveh",
		"police.getoutveh",
		"cop.keycard",
		"police.drag",
		"police.easy_cuff",
		"police.easy_fine",
		"police.easy_jail",
		"police.easy_unjail",
		"police.spikes",
		"police.menu",
		"police.check",
		"toggle.service",
		"police.freeze",
		"police.service",
		"police.wanted",
		"police.seize.weapons",
		"police.seize.items",
		--"police.jail",
		--"police.fine",
		"police.announce",
	-- "-police.store_weapons",
		"-police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
		"police.vehicle",
		"police.loadshop",
		"cop.whitelisted",
		"emergency.market",
		"emergency.revive",
		"emergency.shop",
		--"player.list",
		"police.paycheck",
		"police.mission",
		"player.blips",
		"police.menu_interaction"
	},
	["Superintendent"] = {
		"police.maxarmour",
		"superintendent.pd",
		"police.armoury",
		"cop.keycard",
		"police.group",
		"police.call",
		"pd.armory",
		"Officer.cloakroom",
		"highway.cloakroom",
		"police.pc",
		--"police.handcuff",
		"police.putinveh",
		"police.getoutveh",
		"cop.keycard",
		"police.drag",
		"police.easy_cuff",
		"police.easy_fine",
		"police.easy_jail",
		"police.easy_unjail",
		"police.spikes",
		"police.menu",
		"police.check",
		"toggle.service",
		"police.freeze",
		"police.service",
		"police.wanted",
		"police.seize.weapons",
		"police.seize.items",
		--"police.jail",
		--"police.fine",
		"police.announce",
	-- "-police.store_weapons",
		"-police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
		"police.vehicle",
		"police.loadshop",
		"cop.whitelisted",
		"emergency.market",
		"emergency.revive",
		"emergency.shop",
		--"player.list",
		"police.paycheck",
		"police.mission",
		"player.blips",
		"police.menu_interaction"
	},
	["ChiefInspector"] = {
		"police.maxarmour",
		"chiefinspector.pd",
		"police.armoury",
		"cop.keycard",
		"police.group",
		"police.call",
		"pd.armory",
		"Officer.cloakroom",
		"highway.cloakroom",
		"police.pc",
		--"police.handcuff",
		"police.putinveh",
		"police.getoutveh",
		"cop.keycard",
		"police.drag",
		"police.easy_cuff",
		"police.easy_fine",
		"police.easy_jail",
		"police.easy_unjail",
		"police.spikes",
		"police.menu",
		"police.check",
		"toggle.service",
		"police.freeze",
		"police.service",
		"police.wanted",
		"police.seize.weapons",
		"police.seize.items",
		--"police.jail",
		--"police.fine",
		"police.announce",
	-- "-police.store_weapons",
		"-police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
		"police.vehicle",
		"police.loadshop",
		"cop.whitelisted",
		"emergency.market",
		"emergency.revive",
		"emergency.shop",
		--"player.list",
		"police.paycheck",
		"police.mission",
		"player.blips",
		"police.menu_interaction"
	},
	["Inspector"] = {
	
		"inspector.pd",
		"police.armoury",
		"cop.keycard",
		"police.group",
		"police.call",
		"pd.armory",
	},
	["Sergeant"] = {
	
		"sergeant.pd",
		"police.armoury",
		"cop.keycard",
		"police.group",
		"police.call",
		"pd.armory",
		"Officer.cloakroom",
		"highway.cloakroom",
		"police.pc",
		--"police.handcuff",
		"police.putinveh",
		"police.getoutveh",
		"cop.keycard",
		"police.drag",
		"police.easy_cuff",
		"police.easy_fine",
		"police.easy_jail",
		"police.easy_unjail",
		"police.spikes",
		"police.menu",
		"police.check",
		"toggle.service",
		"police.freeze",
		"police.service",
		"police.wanted",
		"police.seize.weapons",
		"police.seize.items",
		--"police.jail",
		--"police.fine",
		"police.announce",
	-- "-police.store_weapons",
		"-police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
		"police.vehicle",
		"police.loadshop",
		"cop.whitelisted",
		"emergency.market",
		"emergency.revive",
		"emergency.shop",
		--"player.list",
		"police.paycheck",
		"police.mission",
		"player.blips",
		"police.menu_interaction"
	},
	["Senior Constable"] = {
	
		"seniorconstable.pd",
		"police.armoury",
		"cop.keycard",
		"police.group",
		"police.call",
		"pd.armory",
		"Officer.cloakroom",
		"highway.cloakroom",
		"police.pc",
		--"police.handcuff",
		"police.putinveh",
		"police.getoutveh",
		"cop.keycard",
		"police.drag",
		"police.easy_cuff",
		"police.easy_fine",
		"police.easy_jail",
		"police.easy_unjail",
		"police.spikes",
		"police.menu",
		"police.check",
		"toggle.service",
		"police.freeze",
		"police.service",
		"police.wanted",
		"police.seize.weapons",
		"police.seize.items",
		--"police.jail",
		--"police.fine",
		"police.announce",
	-- "-police.store_weapons",
		"-police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
		"police.vehicle",
		"police.loadshop",
		"cop.whitelisted",
		"emergency.market",
		"emergency.revive",
		"emergency.shop",
		--"player.list",
		"police.paycheck",
		"police.mission",
		"player.blips",
		"police.menu_interaction"
	},
	["Police Constable"] = {
	
		"policeconstable.pd",
		"police.armoury",
		"cop.keycard",
		"police.group",
		"police.call",
		"pd.armory",
		"Officer.cloakroom",
		"highway.cloakroom",
		"police.pc",
		--"police.handcuff",
		"police.putinveh",
		"police.getoutveh",
		"cop.keycard",
		"police.drag",
		"police.easy_cuff",
		"police.easy_fine",
		"police.easy_jail",
		"police.easy_unjail",
		"police.spikes",
		"police.menu",
		"police.check",
		"toggle.service",
		"police.freeze",
		"police.service",
		"police.wanted",
		"police.seize.weapons",
		"police.seize.items",
		--"police.jail",
		--"police.fine",
		"police.announce",
	-- "-police.store_weapons",
		"-police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
		"police.vehicle",
		"police.loadshop",
		"cop.whitelisted",
		"emergency.market",
		"emergency.revive",
		"emergency.shop",
		--"player.list",
		"police.paycheck",
		"police.mission",
		"player.blips",
		"police.menu_interaction"
	},
	["PCSO"] = {
	
		"pcso.pd",
		"police.armoury",
		"cop.keycard",
		"police.group",
		"police.call",
		"pd.armory",
		"Officer.cloakroom",
		"highway.cloakroom",
		"police.pc",
		--"police.handcuff",
		"police.putinveh",
		"police.getoutveh",
		"cop.keycard",
		"police.drag",
		"police.easy_cuff",
		"police.easy_fine",
		"police.easy_jail",
		"police.easy_unjail",
		"police.spikes",
		"police.menu",
		"police.check",
		"toggle.service",
		"police.freeze",
		"police.service",
		"police.wanted",
		"police.seize.weapons",
		"police.seize.items",
		--"police.jail",
		--"police.fine",
		"police.announce",
	-- "-police.store_weapons",
		"-police.seizable",	-- negative permission, police can't seize itself, even if another group add the permission
		"police.vehicle",
		"police.loadshop",
		"cop.whitelisted",
		"emergency.market",
		"emergency.revive",
		"emergency.shop",
		--"player.list",
		"police.paycheck",
		"police.mission",
		"player.blips",
		"police.menu_interaction"
	},
	["DJ"] = {
		"dj.menu"
	},
}

-- groups are added dynamically using the API or the menu, but you can add group when an user join here
cfg.users = {
  [1] = { -- give superadmin and admin group to the first created user on the database
    "founder",
	"dev",
  },
  
  [2] = { -- give superadmin and admin group to the first created user on the database
    "founder",
	"dev",
  },
--   [181] = { -- give superadmin and admin group to the first created user on the database
--     "founder",
-- 	"dev",
--   },
--   [455] = { -- give superadmin and admin group to the first created user on the database
--     "founder",
-- 	"dev",
--   },
--   [238] = { -- give superadmin and admin group to the first created user on the database
--     "founder",
-- 	"dev",
--   },
--   [237] = { -- give superadmin and admin group to the first created user on the database
--     "founder",
-- 	"dev",
--   }
}

-- group selectors
-- _config
--- x,y,z, blipid, blipcolor, permissions (optional)

cfg.selectors = {
  
}

return cfg