weaponNames = {}

weaponNames["WT_M4A1"] = "M4A1"
weaponNames["WT_PPSH"] = "PPSH"
weaponNames["WT_SIGMCX"] = "Sig MCX"
weaponNames["WT_AK74"] = "AK74"
weaponNames["WT_RIFLE_SIG"]  = "Sig 516"
weaponNames["WT_AK74Vanquish"] = "AK47 Vanquish"
weaponNames["WT_AKM"] = "AKM"
weaponNames["WT_HOWL"] = "Howl M4"
weaponNames["WT_FNX"] = "FNX 45"
weaponNames["WT_CHUCKY"] = "AK-74u"
weaponNames["WT_L119A2"] = "L119A2"
weaponNames["WT_AK74Neon"] = "AK47 Neon Rider"
weaponNames["WT_AK74Carbon"] = "AK47 Carbon"
weaponNames["WT_LIGHTSABER"] = "Lightsaber"
weaponNames["WT_AK74Assimov"] = "AK47 Assimov"
weaponNames["WT_416D"] = "HK416D"
weaponNames["WT_FAL"] = "Parafal"
weaponNames["WT_AK74Kashnar"] = "AK74 Kashnar"
weaponNames["WT_MOSIN"] = "Mosin"
weaponNames["WT_AWM"] = "AWM F&K"
weaponNames["WT_SNIP_RIF"] = "Kar98k Rifle"
weaponNames["WT_BERRETA"] = "Berreta"
weaponNames["WT_M1911"] = "M1911"
weaponNames["WT_P226"] = "P226 Pistol"
weaponNames["WT_STONER"] = "Stoner 63-A"
weaponNames["WT_M110"] = "M110 Sniper"
weaponNames["WT_FNFAL"] = "FNFAL Rifle"
weaponNames["WT_BARRET"] = "Barret 50cal"
weaponNames["WT_M98"] = "Barret M98 Bravo"
weaponNames["WT_MTAR"] = "MTAR Rifle"
weaponNames["WT_LVOAC"] = "LVOAC Rifle"
weaponNames["WT_HK416"] = "HK 416 Rifle"
weaponNames["WT_SCAR"] = "SCAR H Rifle"
weaponNames["WT_SCARWW3"] = "World War 3 SCAR H"
weaponNames["WT_ACR"] = "ACR Rifle"
weaponNames["WT_ENOR"] = "Deadshot Rifle"
weaponNames["WT_HK"] = "HK417"
weaponNames["WT_SV"] = "SV-98"
weaponNames["WT_TAC"] = "Tactical M4A1 CQB"
weaponNames["WT_SVD"] = "SVD Sniper"
weaponNames["WT_WINCHESTER12"] = "Winchester Model 12"
weaponNames["WT_SCARL"] = "SCAR-L"
weaponNames["WT_FAMAS"] = "FAMAS"
weaponNames["WT_BORA"] = "Bora-12"
weaponNames["WT_HKG3"] = "HKG3"
weaponNames["WT_RE6"] = "RE6"
weaponNames["WT_AKKAL"] = "AK-200"
weaponNames["WT_M4A1T"] = "M4A1"
weaponNames["WT_M4A11"] = "M4A1"
weaponNames["WT_M203"] = "M203"
weaponNames["WT_M4COLT"] = "M4A1 Colt"
weaponNames["WT_RE6SR"] = "RE6 Bolt-Action Sniper Rifle"
weaponNames["WT_M4A1DESERT"] = "M4A1 Desert"
weaponNames["WT_RE6RN"] = "RE6 Assault Rifle RN"
weaponNames["WT_DEVGRU"] = "Devgru Hk416 Eotech"
weaponNames["WT_SP1"] = "M16 SP1"
weaponNames["WT_FAMASG2"] = "Famas G2"
weaponNames["WT_R5"] = "Remington R5 RGP"
weaponNames["WT_FNP"] = "FNP 45"
weaponNames["WT_HK870"] = "HK 870"
weaponNames["WT_MK18"] = "MK18 CQBR"
weaponNames["WT_HK418"] = "HK418 Ghost Recon Wildlands"
weaponNames["WT_CARBINEMK3"] = "Carbine Mk3"
weaponNames["WT_M16VN"] = "M16VN"
weaponNames["WT_G36K"] = "G36K"
weaponNames["WT_VAL"] = "AS Val"
weaponNames["WT_HK416SF"] = "HK416 Silah"
weaponNames["WT_MSBS"] = "MSBS 5.56"
weaponNames["WT_GLOCK17"] = "GLOCK 17"
weaponNames["WT_M16A2"] = "M16A2"
weaponNames["WT_M16A4"] = "M16A4"
weaponNames["WT_MSR"] = "Remington MSR"
weaponNames["WT_OTS"] = "OTS 33"
weaponNames["WT_RIFLEV2"] = "RIFLE V2"
weaponNames["WT_VOM"] = "Vom Feuer"
weaponNames["WT_MP40"] = "MP 40"
weaponNames["WT_HAWK"] = "Hawk M4"
weaponNames["WT_CAR"] = "Car-15"
weaponNames["WT_AR15"] = "AR-15"
weaponNames["WT_AK74U"] = "AK-74u"
weaponNames["WT_POF"] = "POF-P416"
weaponNames["WT_FNPISTOL"] = "Vigilante Pistol"
weaponNames["WT_ACR2"] = "ACR-2"
weaponNames["WT_HK416C"] = "H&K 416c"
weaponNames["WT_HK416F"] = "HK416 Girls Frontline"
weaponNames["WT_MPX"] = "Sig MPX"
weaponNames["WT_EVO"] = "Scorpion EVO 3"
weaponNames["WT_DEAGLE"] = "Deagle .50"
weaponNames["WT_GRAU"] = "Grau 5.56"
weaponNames["WT_M13"] = "M13 Red Tiger"
weaponNames["WT_SPEC"] = "Custom Special Carbine MK2"
weaponNames["WT_MK4"] = "Advanced Carbine MK4"
weaponNames["WT_THOMPSON"] = "Thompson 1928 A1"
weaponNames["WT_UMP45"] = "UMP45"
weaponNames["WT_UMP9"] = "UMP9"
weaponNames["WT_MP7"] = "MP7"
weaponNames["WT_MP5"] = "MP5"
--------------------
---- Rust AK47s ----
--------------------
weaponNames["WT_RUSTAK"] = "Rust AK-47"
weaponNames["WT_REVENGE"] = "AK-47 Kitty Revenge"
weaponNames["WT_HEAVEN"] = "AK-47 From Heaven"
weaponNames["WT_ANGEL"] = "Angel of Death AK-47"
weaponNames["WT_AZUL"] = "Azul AK-47"
weaponNames["WT_BERSERKER"] = "Berserker AK-47"
weaponNames["WT_BLACKOUT"] = "Blackout AK-47"
weaponNames["WT_COLDHUNTER"] = "Cold Hunter AK-47"
weaponNames["WT_MOO"] = "Cow Moo Flage AK-47"
weaponNames["WT_DEATHCHARGER"] = "Death Charger AK-47"
weaponNames["WT_DOODLE"] = "Doodle AK-47"
weaponNames["WT_EPIDEMIC"] = "Epidemic AK-47"
weaponNames["WT_GLORIOUS"] = "Glorious AK-47"
weaponNames["WT_GLORY"] = "Glory AK-47"
weaponNames["WT_GOLDEN"] = "Golden Boss AK-47"
weaponNames["WT_HOLOGRAPHIC"] = "Holographic AK-47"
weaponNames["WT_MONOCHROME"] = "Monochrome AK-47"
weaponNames["WT_NOMERCY"] = "No Mercy AK-47"
weaponNames["WT_ONESHOT"] = "One Shot AK-47"
weaponNames["WT_ORANGELINE"] = "Orange Line AK-47"
weaponNames["WT_OUTPOST"] = "Outpost AK-47"
weaponNames["WT_ROOT9R"] = "Root9r AK-47"
weaponNames["WT_SERWINTER"] = "Ser Winter AK-47"
weaponNames["WT_SINKS"] = "Sinks AK-47"
weaponNames["WT_SPODUMENE"] = "Spodumene AK-47"
weaponNames["WT_SOUL"] = "Street Soul AK-47"
weaponNames["WT_SURVIVOR"] = "Survivor AK-47"
weaponNames["WT_TACTICAL"] = "Tactical AK-47"
weaponNames["WT_TEMPERED"] = "Tempered AK-47"
weaponNames["WT_URBANCAMO"] = "Urban Camo AK-47"
weaponNames["WT_VICTORIA"] = "Victoria AK-47"
weaponNames["WT_WLOVE"] = "Wasteland Love AK-47"
weaponNames["WT_WRECKED"] = "Wrecked AK-47"
weaponNames["WT_XQC"] = "xQc AK-47"
weaponNames["WT_BIOHAZARD"] = "Biohazard AK-47"
---------------------
---- Rust LR300s ----
---------------------
weaponNames["WT_LR300"] = "Rust LR-300"
weaponNames["WT_SURVIVORLR"] = "Survivor LR-300"
weaponNames["WT_ANARCHIST"] = "Anarchist LR-300"
weaponNames["WT_WARHEAD"] = "Warhead LR-300"
---------------------
---- Custom Guns ----
---------------------
weaponNames["WT_516SOPMOD"] = "White Sig 516 Sopmod"
weaponNames["WT_DTMDR"] = "Desert Tech MDR"
weaponNames["WT_SG553"] = "Cold Desert SG553"
weaponNames["WT_GOLDENACR"] = "Golden ACR"

 

Citizen.CreateThread(function()
	for k,v in pairs(weaponNames) do 
		AddTextEntry(k, v)
	end
end)