if not IsDuplicityVersion() then
  CLIENT_CONFIG = {}
  CLIENT_CONFIG.playerModel = 'mp_m_freemode_01'

  CLIENT_CONFIG.squadCoords = {
    right = vector3(46.15, -1028.21, 14.9),
    middle = vector3(45.94, -1026.91, 14.9),
    left = vector3(47.01, -1026.21, 14.9),
  }

  CLIENT_CONFIG.camCoords = vector3(42.27, -1025.16, 15.9)

  CLIENT_CONFIG.allowedVehicles = {
    ['blazer03'] = true,
    ['miljet'] = true,
    ['nimbus'] = true,
    ['rcmavic'] = true,
    ['seashark'] = true,
  }

  CLIENT_CONFIG.supportedKeys = {
    ['1'] = 157,
    ['2'] = 158,
    ['3'] = 160,
    ['4'] = 164,
    ['5'] = 165,
    ['6'] = 159,
    ['7'] = 161,
    ['8'] = 162,
    ['9'] = 163,
    ['A'] = 34,
    ['ARROWDOWN'] = 173,
    ['ARROWLEFT'] = 174,
    ['ARROWRIGHT'] = 175,
    ['ARROWUP'] = 27,
    ['B'] = 29,
    ['C'] = 26,
    ['CAPSLOCK'] = 137,
    ['CONTROL'] = 210,
    ['D'] = 30,
    ['E'] = 46,
    ['F'] = 49,
    ['F1'] = 288,
    ['F10'] = 57,
    ['F11'] = 344,
    ['F2'] = 289,
    ['F3'] = 170,
    ['F5'] = 166,
    ['F6'] = 167,
    ['F7'] = 168,
    ['F8'] = 169,
    ['F9'] = 56,
    ['G'] = 47,
    ['H'] = 74,
    ['K'] = 311,
    ['L'] = 7,
    ['M'] = 244,
    ['N'] = 249,
    ['NONE'] = -1,
    ['P'] = 199,
    ['Q'] = 44,
    ['R'] = 45,
    ['S'] = 33,
    ['SHIFT'] = 21,
    ['SPACE'] = 203,
    ['T'] = 245,
    ['TAB'] = 204,
    ['U'] = 303,
    ['V'] = 236,
    ['W'] = 32,
    ['X'] = 77,
    ['Y'] = 246,
    ['Z'] = 20,
  }

  CLIENT_CONFIG.blacklistedWeapons = {
    GetHashKey('WEAPON_ADVANCEDRIFLE'),
    GetHashKey('WEAPON_AIR_DEFENCE_GUN'),
    GetHashKey('WEAPON_AIRSTRIKE_ROCKET'),
    GetHashKey('WEAPON_APPISTOL'),
    GetHashKey('WEAPON_ASSAULTRIFLE_MK2'),
    GetHashKey('WEAPON_ASSAULTRIFLE'),
    GetHashKey('WEAPON_ASSAULTSHOTGUN'),
    GetHashKey('WEAPON_ASSAULTSMG'),
    GetHashKey('WEAPON_AUTOSHOTGUN'),
    GetHashKey('WEAPON_BALL'),
    GetHashKey('WEAPON_BAT'),
    GetHashKey('WEAPON_BATTLEAXE'),
    GetHashKey('WEAPON_BOTTLE'),
    GetHashKey('WEAPON_BULLPUPRIFLE_MK2'),
    GetHashKey('WEAPON_BULLPUPRIFLE'),
    GetHashKey('WEAPON_BULLPUPSHOTGUN'),
    GetHashKey('WEAPON_CARBINERIFLE_MK2'),
    GetHashKey('WEAPON_CARBINERIFLE'),
    GetHashKey('WEAPON_CERAMICPISTOL'),
    GetHashKey('WEAPON_COMBATMG_MK2'),
    GetHashKey('WEAPON_COMBATMG'),
    GetHashKey('WEAPON_COMBATPDW'),
    GetHashKey('WEAPON_COMBATPISTOL'),
    GetHashKey('WEAPON_COMPACTLAUNCHER'),
    GetHashKey('WEAPON_COMPACTRIFLE'),
    GetHashKey('WEAPON_CROWBAR'),
    GetHashKey('WEAPON_DAGGER'),
    GetHashKey('WEAPON_DBSHOTGUN'),
    GetHashKey('WEAPON_DIGISCANNER'),
    GetHashKey('WEAPON_DOUBLEACTION'),
    GetHashKey('WEAPON_FIREEXTINGUISHER'),
    GetHashKey('WEAPON_FIREWORK'),
    GetHashKey('WEAPON_FLARE'),
    GetHashKey('WEAPON_FLAREGUN'),
    GetHashKey('WEAPON_FLASHLIGHT'),
    GetHashKey('WEAPON_GOLFCLUB'),
    GetHashKey('WEAPON_GRENADELAUNCHER_SMOKE'),
    GetHashKey('WEAPON_GRENADELAUNCHER'),
    GetHashKey('WEAPON_GUSENBERG'),
    GetHashKey('WEAPON_HAMMER'),
    GetHashKey('WEAPON_HATCHET'),
    GetHashKey('WEAPON_HAZARDCAN'),
    GetHashKey('WEAPON_HEAVYPISTOL'),
    GetHashKey('WEAPON_HEAVYSHOTGUN'),
    GetHashKey('WEAPON_HEAVYSNIPER_MK2'),
    GetHashKey('WEAPON_HEAVYSNIPER'),
    GetHashKey('WEAPON_HOMINGLAUNCHER'),
    GetHashKey('WEAPON_KNIFE'),
    GetHashKey('WEAPON_KNUCKLE'),
    GetHashKey('WEAPON_MACHETE'),
    GetHashKey('WEAPON_MACHINEPISTOL'),
    GetHashKey('WEAPON_MARKSMANPISTOL'),
    GetHashKey('WEAPON_MARKSMANRIFLE_MK2'),
    GetHashKey('WEAPON_MARKSMANRIFLE'),
    GetHashKey('WEAPON_MG'),
    GetHashKey('WEAPON_MICROSMG'),
    GetHashKey('WEAPON_MINIGUN'),
    GetHashKey('WEAPON_MINISMG'),
    GetHashKey('WEAPON_MUSKET'),
    GetHashKey('WEAPON_NAVYREVOLVER'),
    GetHashKey('WEAPON_NIGHTSTICK'),
    GetHashKey('WEAPON_PASSENGER_ROCKET'),
    GetHashKey('WEAPON_PETROLCAN'),
    GetHashKey('WEAPON_PIPEBOMB'),
    GetHashKey('WEAPON_PIPEWRENCH'),
    GetHashKey('WEAPON_PISTOL_MK2'),
    GetHashKey('WEAPON_PISTOL'),
    GetHashKey('WEAPON_PISTOL50'),
    GetHashKey('WEAPON_POOLCUE'),
    GetHashKey('WEAPON_PROXMINE'),
    GetHashKey('WEAPON_PUMPSHOTGUN_MK2'),
    GetHashKey('WEAPON_PUMPSHOTGUN'),
    GetHashKey('WEAPON_RAILGUN'),
    GetHashKey('WEAPON_RAYCARBINE'),
    GetHashKey('WEAPON_RAYMINIGUN'),
    GetHashKey('WEAPON_RAYPISTOL'),
    GetHashKey('WEAPON_REVOLVER_MK2'),
    GetHashKey('WEAPON_REVOLVER'),
    GetHashKey('WEAPON_RPG'),
    GetHashKey('WEAPON_SAWNOFFSHOTGUN'),
    GetHashKey('WEAPON_SMG_MK2'),
    GetHashKey('WEAPON_SMG'),
    GetHashKey('WEAPON_SMOKEGRENADE'),
    GetHashKey('WEAPON_SNIPERRIFLE'),
    GetHashKey('WEAPON_SNOWBALL'),
    GetHashKey('WEAPON_SNSPISTOL_MK2'),
    GetHashKey('WEAPON_SNSPISTOL'),
    GetHashKey('WEAPON_SPECIALCARBINE_MK2'),
    GetHashKey('WEAPON_SPECIALCARBINE'),
    GetHashKey('WEAPON_STICKYBOMB'),
    GetHashKey('WEAPON_STONE_HATCHET'),
    GetHashKey('WEAPON_STUNGUN'),
    GetHashKey('WEAPON_SWEEPERSHOTGUN'),
    GetHashKey('WEAPON_SWITCHBLADE'),
    GetHashKey('WEAPON_VINTAGEPISTOL'),
    GetHashKey('WEAPON_WRENCH'),
  }

  CLIENT_CONFIG.animList = {
    ['hi_dance_crowd_15_v2_female^1'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_15_v2_female^2'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_15_v2_female^3'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_15_v2_female^4'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_15_v2_female^5'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_15_v2_female^6'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_15_v2_male^1'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_15_v2_male^2'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_15_v2_male^3'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_15_v2_male^4'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_15_v2_male^5'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_15_v2_male^6'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_17_v1_female^1'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_17_v1_female^2'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_17_v1_female^3'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_17_v1_female^4'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_17_v1_female^5'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_17_v1_female^6'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_17_v1_male^1'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_17_v1_male^2'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_09_v1_female^1'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_17_v1_male^3'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_09_v1_female^2'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_17_v1_male^4'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_17_v1_male^5'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_09_v1_female^3'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_17_v1_male^6'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_17_v2_female^1'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_09_v1_female^4'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_17_v2_female^2'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_17_v2_female^3'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_09_v1_female^5'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_17_v2_female^4'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_17_v2_female^5'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_09_v1_female^6'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_17_v2_female^6'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_09_v1_male^1'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_17_v2_male^1'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_17_v2_male^2'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_09_v1_male^2'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_17_v2_male^3'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_17_v2_male^4'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_09_v1_male^3'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_17_v2_male^5'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_17_v2_male^6'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_09_v1_male^4'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_09_v1_male^5'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_09_v1_male^6'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_09_v2_female^1'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_09_v2_female^2'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_09_v2_female^3'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_09_v2_female^4'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_09_v2_female^5'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_09_v2_female^6'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_09_v2_male^1'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_09_v2_male^2'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_09_v2_male^3'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_09_v2_male^4'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_09_v2_male^5'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_09_v2_male^6'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_11_v1_female^1'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_11_v1_female^2'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_11_v1_female^3'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_11_v1_female^4'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_11_v1_female^5'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_11_v1_female^6'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_11_v1_male^1'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_11_v1_male^2'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_11_v1_male^3'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_11_v1_male^4'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_11_v1_male^5'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_11_v1_male^6'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_13_v2_female^1'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_13_v2_female^2'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_13_v2_female^3'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_13_v2_female^4'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_13_v2_female^5'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_13_v2_female^6'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_13_v2_male^1'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_13_v2_male^2'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_13_v2_male^3'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_13_v2_male^4'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_13_v2_male^5'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_13_v2_male^6'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_15_v1_female^1'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_15_v1_female^2'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_15_v1_female^3'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_15_v1_female^4'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_15_v1_female^5'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_15_v1_female^6'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_15_v1_male^1'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_15_v1_male^2'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_15_v1_male^3'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_15_v1_male^4'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_15_v1_male^5'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
    ['hi_dance_crowd_15_v1_male^6'] = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
  }

  CLIENT_CONFIG.protectedNatives = {
    ['AddAmmoToPed'] = AddAmmoToPed,
    ['AddBlipForCoord'] = AddBlipForCoord,
    ['AddBlipForEntity'] = AddBlipForEntity,
    ['AddExplosion'] = AddExplosion,
    ['AddTextComponentString'] = AddTextComponentString,
    ['ApplyForceToEntity'] = ApplyForceToEntity,
    ['AttachEntityToEntity'] = AttachEntityToEntity,
    ['ClearPedTasksImmediately'] = ClearPedTasksImmediately,
    ['ClearPlayerWantedLevel'] = ClearPlayerWantedLevel,
    ['ClonePed'] = ClonePed,
    ['CreateAmbientPickup'] = CreateAmbientPickup,
    ['CreateCam'] = CreateCam,
    ['CreateCamera'] = CreateCamera,
    ['CreateCameraWithParams'] = CreateCameraWithParams,
    ['CreateCamWithParams'] = CreateCamWithParams,
    ['CreateDui'] = CreateDui,
    ['CreateObject'] = CreateObject,
    ['CreateObjectNoOffset'] = CreateObjectNoOffset,
    ['CreatePed'] = CreatePed,
    ['CreatePedInsideVehicle'] = CreatePedInsideVehicle,
    ['CreatePickup'] = CreatePickup,
    ['CreatePickUpRopeForCargobob'] = CreatePickUpRopeForCargobob,
    ['CreatePickupRotate'] = CreatePickupRotate,
    ['CreateVehicle'] = CreateVehicle,
    ['DrawLine'] = DrawLine,
    ['DrawNotification'] = DrawNotification,
    ['DrawText'] = DrawText,
    ['EndTextCommandDisplayHelp'] = EndTextCommandDisplayHelp,
    ['EndTextCommandDisplayText'] = EndTextCommandDisplayText,
    ['ForceSocialClubUpdate'] = ForceSocialClubUpdate,
    ['GetCurrentServerEndpoint'] = GetCurrentServerEndpoint,
    ['GetPlayerName'] = GetPlayerName,
    ['GetResourceState'] = GetResourceState,
    ['GiveWeaponToPed'] = GiveWeaponToPed,
    ['NetworkExplodeVehicle'] = NetworkExplodeVehicle,
    ['NetworkIsPlayerActive'] = NetworkIsPlayerActive,
    ['NetworkResurrectLocalPlayer'] = NetworkResurrectLocalPlayer,
    ['NetworkSetInSpectatorMode'] = NetworkSetInSpectatorMode,
    ['print'] = print,
    ['PushScaleformMovieFunction'] = PushScaleformMovieFunction,
    ['RefillAmmoInstantly'] = RefillAmmoInstantly,
    ['RegisterCommand'] = RegisterCommand,
    ['RemoveAllPedWeapons'] = RemoveAllPedWeapons,
    ['RemoveEventHandler'] = RemoveEventHandler,
    ['RemoveWeaponFromPed'] = RemoveWeaponFromPed,
    ['RequestScaleformMovie'] = RequestScaleformMovie,
    ['ResetPlayerStamina'] = ResetPlayerStamina,
    ['RestorePlayerStamina'] = RestorePlayerStamina,
    ['SetAiMeleeWeaponDamageModifier'] = SetAiMeleeWeaponDamageModifier,
    ['SetAiWeaponDamageModifier'] = SetAiWeaponDamageModifier,
    ['SetBlipSprite'] = SetBlipSprite,
    ['SetDiscordAppId'] = SetDiscordAppId,
    ['SetDiscordRichPresenceAction'] = SetDiscordRichPresenceAction,
    ['SetDiscordRichPresenceAsset'] = SetDiscordRichPresenceAsset,
    ['SetEntityCoords'] = SetEntityCoords,
    ['SetEntityCoordsNoOffset'] = SetEntityCoordsNoOffset,
    ['SetEntityCoordsWithoutPlantsReset'] = SetEntityCoordsWithoutPlantsReset,
    ['SetEntityHealth'] = SetEntityHealth,
    ['SetEntityInvincible'] = SetEntityInvincible,
    ['SetEntityProofs'] = SetEntityProofs,
    ['SetEntityVisible'] = SetEntityVisible,
    ['SetNightvision'] = SetNightvision,
    ['SetNotificationTextEntry'] = SetNotificationTextEntry,
    ['SetPedAmmo'] = SetPedAmmo,
    ['SetPedArmour'] = SetPedArmour,
    ['SetPedCanRagdoll'] = SetPedCanRagdoll,
    ['SetPedComponentVariation'] = SetPedComponentVariation,
    ['SetPedInfiniteAmmo'] = SetPedInfiniteAmmo,
    ['SetPedInfiniteAmmoClip'] = SetPedInfiniteAmmoClip,
    ['SetPedParachuteTintIndex'] = SetPedParachuteTintIndex,
    ['SetPedPropIndex'] = SetPedPropIndex,
    ['SetPedRandomComponentVariation'] = SetPedRandomComponentVariation,
    ['SetPedShootsAtCoord'] = SetPedShootsAtCoord,
    ['SetPlayerInvincible'] = SetPlayerInvincible,
    ['SetPlayerMeleeWeaponDamageModifier'] = SetPlayerMeleeWeaponDamageModifier,
    ['SetPlayerMeleeWeaponDefenseModifier'] = SetPlayerMeleeWeaponDefenseModifier,
    ['SetPlayerStealthPerceptionModifier'] = SetPlayerStealthPerceptionModifier,
    ['SetPlayerVehicleDamageModifier'] = SetPlayerVehicleDamageModifier,
    ['SetPlayerVehicleDefenseModifier'] = SetPlayerVehicleDefenseModifier,
    ['SetPlayerWeaponDamageModifier'] = SetPlayerWeaponDamageModifier,
    ['SetPlayerWeaponDefenseModifier_2'] = SetPlayerWeaponDefenseModifier_2,
    ['SetPlayerWeaponDefenseModifier'] = SetPlayerWeaponDefenseModifier,
    ['SetRunSprintMultiplierForPlayer'] = SetRunSprintMultiplierForPlayer,
    ['SetSeethrough'] = SetSeethrough,
    ['SetSuperJumpThisFrame'] = SetSuperJumpThisFrame,
    ['SetSwimMultiplierForPlayer'] = SetSwimMultiplierForPlayer,
    ['SetTextEntry'] = SetTextEntry,
    ['SetVehicleDirtLevel'] = SetVehicleDirtLevel,
    ['SetVehicleDoorBroken'] = SetVehicleDoorBroken,
    ['SetVehicleEngineHealth'] = SetVehicleEngineHealth,
    ['SetVehicleTyreBurst'] = SetVehicleTyreBurst,
    ['SetWeaponDamageModifierThisFrame'] = SetWeaponDamageModifierThisFrame,
    ['ShootSingleBulletBetweenCoords'] = ShootSingleBulletBetweenCoords,
    ['SmashVehicleWindow'] = SmashVehicleWindow,
    ['StartEntityFire'] = StartEntityFire,
    ['StartScriptFire'] = StartScriptFire,
    ['TriggerEvent'] = TriggerEvent,
    ['TriggerEventInternal'] = TriggerEventInternal,
    ['TriggerServerEvent'] = TriggerServerEvent,
    ['TriggerServerEventInternal'] = TriggerServerEventInternal,
  }
end

