AddTextEntry("WEAPON_SHOVEL", "Shovel")
AddTextEntry("WEAPON_DILDO", "Dildo")
AddTextEntry("WEAPON_AXE", "Axe")
AddTextEntry("WEAPON_BASEBALLBAT", "Baseball Bat")
AddTextEntry("WEAPON_BROOM", "Broom")
AddTextEntry("WEAPON_DIAMONDSWORD", "Diamond Sword")
AddTextEntry("WEAPON_SHANK", "Shank")
AddTextEntry("WEAPON_AK47", "AK47")
AddTextEntry("WEAPON_AK200", "AK200")
AddTextEntry("WEAPON_MOSIN", "Mosin")
AddTextEntry("WEAPON_UZI", "UZI")
AddTextEntry("WEAPON_WINCHESTER12", "Winchester 12")
AddTextEntry("WEAPON_AK74KASHNAR", "AK74 Kashnar")
AddTextEntry("WEAPON_M4A1", "M4A1")
AddTextEntry("WEAPON_SPAR16", "Spar 16")
AddTextEntry("WEAPON_SVD", "SVD")
AddTextEntry("WEAPON_M1911", "M1911")
AddTextEntry("WEAPON_REVOLVER357", "Revolver 357")
AddTextEntry("WEAPON_TEC9", "Tec-9")
AddTextEntry("WEAPON_STAFFGUN", "Staff Gun")
AddTextEntry("WEAPON_ROOK", "Rook 40")
AddTextEntry("WEAPON_UMP45", "UMP45")
AddTextEntry("WEAPON_CHERRYMOSIN", "Cherry Blossom Mosin")
AddTextEntry("WEAPON_BLASTXPHANTOM", "Blast-X Phantom")
AddTextEntry("WEAPON_M4A1WHITENOISE", "M4A1 Whitenoise")
AddTextEntry("WEAPON_M4A4FIRE", "M4A4 Fire")
AddTextEntry("WEAPON_VTSGLOW", "VTS Glow")
AddTextEntry("WEAPON_SPAR17", "Spar 17")
AddTextEntry("WEAPON_REMINGTON700", "Remington 700")
AddTextEntry("WEAPON_GLOCK", "GLOCK")
AddTextEntry("WEAPON_MP5", "MP5")
AddTextEntry("WEAPON_REMINGTON870", "Remington 870")
AddTextEntry("WEAPON_CQ300", "CQ300")
AddTextEntry("WEAPON_PDHK416", "HK416")
AddTextEntry("WEAPON_PDMCX", "Sig MCX")
AddTextEntry("WEAPON_FLASHBANG", "Flashbang")
AddTextEntry("WEAPON_NERFMOSIN", "Nerf Mosin")
